### ISSUE TITLE
Going to https://www.trustroots.org/about shouldn't change the window.location

### ISSUE THREAD

**Issue by Akronix** [Trustroots/trustroots#1024]
**Describe the bug**
Going to "https://www.trustroots.org/about" doesn't do any redirect but changes the window.location.href to "https://www.trustroots.org".

**To Reproduce**
1. Go to https://www.trustroots.org/about'. No matter if you are logged in or not.
2. Check location bar of your browser, it has automatically changed to https://www.trustroots.org/

**Expected behavior**
Leave the location to https://www.trustroots.org/about

**Additional context**
Maybe it isn't actually a bug but it's quite unexpected from an user point of view.

**Comment by simison** [comment]
It's because the about page is no more. :-) (_Long live the about page!_)

There used to be separate about page and the home page was just one image + signup link. I made the home page much lengthier and elaborate some time in 2016 and that made the separate about page redundant. I left a simple redirect in case there were any links to that page left somewhere around: https://github.com/Trustroots/trustroots/commit/ae2eaf5bb5485ec78b592a3281d5b7d93d811c79

Where did you find a link to that page?

**Comment by Akronix** [comment]
I think I just made up the link.
But I was looking for a link to the page with the principles, manifesto and all the trustroots info, so I could share it with others, even if I or they are signed in. Is there any other url to that?
