### ISSUE TITLE
Remove shop link

### ISSUE THREAD

**Issue by sitarane** [Trustroots/trustroots#1430]
There's a link to [shop.trustroots.org](https://shop.trustroots.org/) in the User menu (top right).

The link takes you to an error page:

![Screenshot from 2020-04-26 12-02-52](https://user-images.githubusercontent.com/10289010/80304481-68301280-87b6-11ea-8be6-80fc91ce2eed.png)

The "more info" link is to [Website Integration with JavaScript ](https://help.spreadshop.com/hc/en-us/articles/360010529039) on Spreadshirt.

**Comment by simison** [comment]
We should just remove the link unless we want to set this up again. 

It wasn't popular.

**Comment by sitarane** [comment]
So, I thought to myself I might as well do it and get friendly with the code base.

I found the 'shop.trustroots.org' in a bunch of files:

modules/core/server/views/partials/header.server.view.html
modules/pages/client/views/navigation.client.view.html
modules/pages/client/views/home.client.view.html
deploy/files/prod-conf/nginx-shop.conf
deploy/ansible/roles/trustroots/templates/nginx/nginx-shop.conf

I would assume the last one is part of some ansible playbook, the one before is whatever we used before ansible. Not sure what to do about those.

Of the first three, there's the homepage for anons. Fine. But then there are two redundant views:

modules/core/server/views/partials/header.server.view.html
modules/pages/client/views/navigation.client.view.html

The one expressed in trustroots seems to be core/server. But then what's the other? Fossilized remnant of a distant past? One is Angular, the other React?

Tagging @Akronix cause latest commit to one and @nicksellen cause latest commit to the other.

**Comment by simison** [comment]
@sitarane Thanks! 

`deploy/*` files are not in use currently and you can ignore those.

All the files in `modules/*` need updating. `navigation.client.view.html` is used when opening navigation for mobile, since navigation has different constraints for mobile clients and thus cannot be simply re-used from desktop version:

<img width="232" alt="image" src="https://user-images.githubusercontent.com/87168/80452620-502fce80-892f-11ea-9149-f31a0670a8da.png">

You can test it by making your browser window narrower.
