### ISSUE TITLE
Phone number and address

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#159]
- Adding phone number and address fields to the profile
- Hidden by default
- Possibility to attach them to message when replying to a hosting request #123 

Especially for hitchhikers it's handy to have phone numbers at profile, just like Warmshowers.org has.

**Comment by platschi** [comment]
Additionally to address maybe 'hitching directions' to your host". I often just make a few hitching direction notes myself using gmaps/osm/whatever before hitching to somebody. This info provided by the actual local hitcher who knows best how to get to his place might be even more awesome

**Comment by guaka** [comment]
I like the idea of hitching directions. Maybe this type of "hosting info"
can be related to groups/communities joined by somebody?

hitchhikers hosting info: if you're trying to hitch into Berlin from the
west, the Michendorf gas station can be a good place to find a ride
straight into Berlin
vegan/vegetarians hosting info: please don't bring meat into our house
parents hosting info: our home is child-proof and we have plenty of toys
musicians hosting info: [no need to enter info here, so left empty]
etc.

Or does that get too convoluted and complicated?

It might be better to instead encourage people to read/add/edit this kind
of stuff: http://hitchwiki.org/en/Berlin#Hitching_In

**Comment by libertedeparole** [comment]
Having hitched a lot, the idea of directions for how to get TO my place by hitching seems rather complicated. There are so many directions people can be coming from. It would be most useful in large heavy urban areas where people may need to get "long short" rides to get within walking distance of their final destination. But a hitcher seldom knows where the winds will take them in these situations. If I get a ride from Barcelona to Madrid, I won't have the slightest idea where in Madrid I will get let off, nor do I care. I can't imagine telling people how to navigate through Paris, for example. In places where there are major hitching arteries, it would seem that better tools should exist on hitching sites - encouraging members to post there also avoids members rewriting the wheel and duplicating work. (But that could be an ideal opportunity in the profile to link to a hitching site(s).) Usually in smaller places, simply giving a nearby landmark would let people tell helpful drivers where they are headed for. 

Otherwise, careful we don't compartmentalize too much. The kind of info Kasper mentions about vegans/parents/etc shouldn't give people who are not in those groups the impression it doesn't concern them. I understand you guys have this idea of communities and want to run with it, but for me the entire idea of hospex is also about encountering people from communities I'm not active in.

**Comment by simison** [comment]
+1 @libertedeparole, avoid too much compartmentalize (while having extra features for [some communities](https://github.com/Trustroots/trustroots/milestones/hackercouch) still makes sense!)

It might get a bit complicated quickly and UI too cluttered. Usually "avoid adding extra textfield at all cost". ;-)

What we could do pretty easily is to add textual guide: "Please add also instructions how to find to your place" and somehow state from which community other party is writing from. That box on the right at messaging showing mainly languages is perfect for that.

Additionally we'll have some kind of geo landing pages #118 at some point where we can show wiki content. We can add a link to this geopage from hosting request discussion.

**Comment by guaka** [comment]
Yay for simplicity :)

**Comment by doktorhorst** [comment]
I'm just talking to another Trustee and we're wondering: Is it intended that profiles do not have a public phone number field?
