### ISSUE TITLE
How to keep quality high?

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#173]
Just got my first TR request with "I tried to find a hostel or something to stay but its not so cheap."

What to do about people who think it's fine to send such requests?

**Comment by jancborchardt** [comment]
We need some kind of community guidelines or code of conduct. Kind of like the [Rules](https://www.trustroots.org/#!/rules), [About/Manifesto](https://www.trustroots.org/#!/about) and [FAQ](https://www.trustroots.org/#!/faq) but more concise and to the point of how hospitality and this network is different from hostels and not just cheap accomodation.

Another thing which will probably get important in the long run would be some kind of »Report person« feature. Every network likes to pretend they don’t need it, but it’s really important to keep harassment at bay. That could entail:
* Making a private note about slight misbehavior of this person which could be shown to your friends for them to be cautious
* Reporting them in a way which admins can see and act upon
* Blocking them from contacting you

**Comment by simison** [comment]
(This is also tightly connected with yet to be implemented communities feature.)

**Comment by NoryDev** [comment]
Hi guys, related question:
In my view, if TR is supposed to be hitch-hikers friendly, it must have a degree of:
- spontaneousness (wannabe guest asking the same day, because they just arrived in the city, or 1 day before)
- "root" attitude: the guest don't expect a palace (private room, bedsheets, towels, etc), and the host don't expect too much from the guest.
I try to explain my remark about hosts expecting too much: on CS there is a lot of profile I find very bobo: hosts expect guests to ask 3 weeks in advance, spend at least 3 nights somewhere and cook a thaï meal while playing some guitar to them. It does not fit with hitch-hiking where your plans are changing, not very timely precise, and you don't necessarily want to stay very long somewhere (say I go from Berlin to Barcelona, I'll be glad to stop for an afternoon/night/morning at somebody in Geneva, but maybe not 3 days).
So finally the related question: how to prevent TR to become a catalog of bobo profiles and remain good for hitch hikers? Or tell me if my view of TR is wrong.

**Comment by libertedeparole** [comment]
NoryDev, I've had many hitchers at my place, none has complained about having a bed and other "luxuries". ;-))  And they have certainly been the most likely to play some music for/with me. It's true that on CS you can find a lot of controlling asshole hosts expecting worship from their guests. I think it is perhaps best to give freedom of speech to those people, let them hang themselves!

**Comment by simison** [comment]
Closing this, follow ups at #208 #207 #219 #196 #136
