### ISSUE TITLE
set up non profit

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#174]
I want a legal entity for Trustroots before Summer. Sooner = better.

I'm leaning towards the UK for this. 
Great official info here: https://www.gov.uk/set-up-a-social-enterprise

More specifically a UK CIC, not a charity: less paperwork. Looks like it's possible to convert a CIC into a charity at a later point. I understood from friends that it's possible to set up a CIC through online forms.
http://www.thirdsector.co.uk/to-decide-charitable-cic-status/governance/article/634004

Note that if someone has experience or is willing to learn a lot about UK charities I'm open to this path as well. (I might be that someone but unlikely.)

**Comment by libertedeparole** [comment]
"setting limits to the money it can pay to shareholders" This would imply that shareholders can receive money - dividends? salary? 

As far as paperwork, there is certainly more for this CIC than for setting up a non-profit in France, though dealing in English is certainly easier for the TR crew. I can't comment about the non-profits paperwork in other countries.

**Comment by libertedeparole** [comment]
BTW, I don't know if the UK follows the same pattern as other countries, such as the US or France, but the paperwork for a "registered charity" is often much higher than for a legal "non-profit". In both France and the US (depends upon the state), non-profits can do everything a charity can within the framework of TR. Countries often have several different classes of non-profit organizations.

**Comment by guaka** [comment]
"setting limits to the money it can pay to shareholders" This would imply
that shareholders can receive money - dividends? salary?

From my limited understanding it's basically that it's a Ltd with statutes
stating there can be no dividends/profit. Also, shareholders can receive a
salary, but not board members.

Apart from that, main question that popped up thinking about this is if
it's easy for a UK non-profit to create a EUR account in another EU country.

**Comment by simison** [comment]
Also:
- is it possible to have EUR account in UK bank? (This was possible e.g. in Lithuania when we had Litas)
- what kind of procedure tax declarations are there?
- rules for meetings (e.g. in Finland one mandatory official one)
- initial cash? Sometimes even nonprofits are required to have quite hefty sum at the beginning.
- credit card? most of the expenses are convenient to pay via credit card. Or the way around is that  one of us pays them and bills the nonprofit for expenses.

**Comment by guaka** [comment]
Cash requirement for charity is 5k GBP, didn't see any requirement for CIC
non-profit.

**Comment by otupman** [comment]
Hey all - as mentioned a UK CIC is essentially a standard UK Ltd company, but must have a social benefit approach and gets all it's assets locked-in. It's convertible to a charity (and vice versa). 

Having just spun up a UK Ltd company, a CIC is, at it's simplest, relatively straightforward to setup as long as you don't want any special extras. The standard UK Ltd formation applies - decide by shares or guarantee, provide memorandum of association & article of association (there are model ones that can be used) and, extra for CICs, a [declaration of community interest](https://www.gov.uk/government/publications/form-cic36-application-to-form-a-community-interest-company) (essentially a list of "service provided" and who benefits from the service).

Shares or guarantee is probably easy to answer - by shares, because otherwise your members will be liable for any bills the CIC runs up (think worst case: lawsuit). 

The memorandum of association & articles of association are probably the trickiest part, unless you decide to simply go with the [model ones](https://www.gov.uk/government/publications/community-interest-companies-constitutions) to at least get it started and change them later _but_ you still have to decide upon an ["asset locked" body](https://www.gov.uk/government/publications/community-interest-companies-constitutions/cic-model-constitutions-introduction#the-asset-locked-body) that would receive the CIC's assets in the event of it's dissolution.  The body must be another charitable/social benefit organisation in the UK or an equivalent outside of the UK (for which evidence must be supplied).

>rules for meetings (e.g. in Finland one mandatory official one)
> initial cash? Sometimes even nonprofits are required to have quite hefty sum at the beginning.

Simplest solution would probably be a CIC with a model memorandum and association and set the asset-locked body as Bewelcome (seeing as they exist within the same space) and your initial shareholders contribute the minimum share value of £1.

From what I understand, dividends _could_ be paid out to shareholders, however I believe with the right articles of association you can either restrict that or only allow it via a member vote.

> what kind of procedure tax declarations are there?

Tax for the CIC itself should be covered by standard UK Ltd tax rules, but with a small extra for CIC - [more info here](https://www.gov.uk/government/publications/community-interest-companies-business-activities/cic-business-activites-step-by-step-guidelines#file-an-annual-cic-report-and-accounts-with-a-15-fee). 

_Individually_, however, I would assume that as directors you'd be liable for tax within the country you're tax resident. I would guess that with a CIC being nearly a Ltd company, at worst you'd report the CIC as being a EU-based corporation for of you are a shareholder.

> is it possible to have EUR account in UK bank? (This was possible e.g. in Lithuania when we had Litas) way around is that one of us pays them and bills the nonprofit for expenses.

The benefit of a CIC is that it's a limited company, so it should be able to benefit from the same banking as any Ltd company so for example a quick google says [Llyods](http://www.lloydsbank.com/business/retail-business/international/euro-accounts.asp) would provide a EUR account.

The issue with bank accounts is that you'll be at the mercy of the bank to decide if they want to give you an account. You can't apply for one without having setup the CIC, though a visit to a bank might get some answers. 

> credit card? most of the expenses are convenient to pay via credit card. Or the 

Same as banking - standard ltd company rules _but_ the bank could decide not to issue one.

> rules for meetings (e.g. in Finland one mandatory official one)

Same as a UK Ltd company which would be defined in the articles of association as to how that would work. Thankfully I _believe_ these days the meeting can occur virtually.

>  I understood from friends that it's possible to set up a CIC through online forms.

My feeling is no, going by [these instructions on HMRC](https://www.gov.uk/government/publications/community-interest-companies-business-activities/cic-business-activites-step-by-step-guidelines#form-a-community-interest-company-cic)



Having said all of that, I would probably reframe the question to something about what exactly are you trying to achieve by considering a non-profit structure. One other option that turned up in the research we did was of [Assembly](https://assembly.com/about), who, to quote 

> Unlike traditional companies with shareholders and employees, everything on Assembly is created, operated, and owned by a global community of makers, together


_Disclaimer:_ I'm not an expert, nothing I say is legally binding, I just happen to have looked into this for [another project](http://andshare.co) to do with the sharing economy which involved similar thoughts and research.

**Comment by simison** [comment]
So just to understand better; is CIC always a cooperative as well, or not? I'm just quickly skimming through [this](http://www.sagepub.com/ridleyduff/Student%20resources/Additional%20case%20studies/Chapter%207/Case%207-2%20-%20Co-operative%20CIC%20%28Critique%29.pdf) now.

**Comment by libertedeparole** [comment]
No, CICs are not always cooperatives, the document Mikael mentioned comes from a cooperative perspective. 

One of the reasons mentioned for creating CICs is that, unlike UK charities, they allow founders to retain complete control of an organization. The UK structure seems, at first glance, to be superior to the US "benefit corporation" legislation (this is what CS tried to imply it had, but actually never even applied for), providing more protection against exploitation of the status. US benefit corporations are traditional businesses that are not bound by US law to privilege profit above all other things. UK CICs are actually limited concerning the amount of profit investors can receive.

Here is from a document from the UK agency with overview:
"We think a balance can be struck between the
flexibility needed by CICs to raise finance
and the need to provide a meaningful asset lock. 
Although investors have the possibility of
making a modest return, when investing in a CIC 
limited by shares this is restricted in
order to ensure that the main
beneficiary of the CIC is the wider community. One of the
aims of the CIC proposals is to expand 
the access to finance available to community
organisations, permitting them to
offer a reasonable return to in
vestors is key to achieving this." 

The "modest return" mentioned was at first a maximum of 20% annual, 
but has since been increased to 35%, which can be accumulated over 5 years. (First page link below.) While these are large rates of return, they do not allow venture capital type profits where the value of investment can be multiplied by thousands.

Here are links to the UK regulator with full information from the official POV 
(this of course doesn't explain possible techniques for exploiting the legislation):

https://www.gov.uk/government/organisations/office-of-the-regulator-of-community-interest-companies

https://www.gov.uk/government/publications/community-interest-companies-introduction


Frequently Asked Questions
organisations, permitting them to
offer a reasonable return to in
vestors is key to achieving
this.

**Comment by guaka** [comment]
Interesting. Is it possible to set it up more non-profity statutes, or
rather less-profit, e.g. by limiting the "modest" return to 10% or less?

sent from my tablet

**Comment by libertedeparole** [comment]
"Interesting. Is it possible to set it up more non-profity statutes, or 
rather less-profit, e.g. by limiting the "modest" return to 10% or less? "

My impression is that a CIC can be much more restrictive, possibly completely disallowing dividends. But that may mean not using standard legal model bylaws, which poses the higher bar of needing to understand the laws and write accordingly, probably using a specialized lawyer. In contrast, non-profit structures like a French Association (this is what I am familiar with, I know that is not the direction you want to go) make dividends completely impossible, so standard bylaws can be used - or special bylaws written without risk. 

In my limited understanding, a British CIC cannot be transformed into a normal Corporation, but it could always be returned to most-favorable status for investors (a change in bylaws seems to need approval by he regulatory agency). Being a Limited Company, membership could not be opened to the general TR public under the manner the law was intended. I think membership would always be conditioned on someone buying shares - perhaps at 1 penny - but the redtape would remain. 

Please realize this is brainstorming, I have no special knowledge of the CIC law beyond what I have read on their site.

CIC was intended as a bridge between private business and social goals allowing private investment and profitable return on investment (and not just donations). However it doesn't seem to reward anyone directly for the work of volunteers. Like most charities and other non-profits, it may legally pay employees virtually unlimited salaries and benefits.

**Comment by simison** [comment]
We've been looking at SCIO instead of CIC, here's a quick reference: https://github.com/Trustroots/trustroots/wiki/SCIO%3F

**Comment by libertedeparole** [comment]
I don't understand the comment, which SHOULD people be looking at? SCIO is Scottish.

**Comment by simison** [comment]
At the moment SCIO looks very good to us, easier to setup than CIC. I'll give more lengthy update (or perhaps I'll open a new thread) once I'm more awake.

**Comment by libertedeparole** [comment]
Thanks Mikael. Glad there's been progress on the issue. It will be interesting to hear the advantages of this legal structure. I have heard that Scottish red tape is thicker than English. Does TR have someone on the ground in Scotland? It sounds like that is a requirement?

**Comment by simison** [comment]
This: http://ideas.trustroots.org/2015/03/10/announcing-trustroots-foundation/
