### ISSUE TITLE
Differentiating Contacts Trust Level

### ISSUE THREAD

**Issue by noahsmindfuck** [Trustroots/trustroots#2089]
**Regarding Contacts on TR**
Since the recent(?) influx of former CS members I see an increase of ppl registering and starting their "life"(?) on TR by sending sporadic contact requests to people.

I find this disturbing as I believe that the contacts feature is meant as a trust mechanism and as soon as ppl start to just collect contacts to have trustworthy profiles (which is imho happening) the whole feature loses its function.
I suggest that when sending a contact request we add a checkbox/radio button/etc. where you can explain to

- the person that you are sending the request to
- anyone who later sees your contact on the profile
- a data collecting algorithm from us
why you are asking for the contact.

This way it becomes transparent, how people are connected and trust can be established through this transparency and additionally we can measure how much the feature is actually used for each purpose.

Any additional ideas on how to better frame the feature, maybe keeping in mind, that at some point one will have 'experiences' #1493  that can actually combined with contacts?

Differentiating between contacts with/without experiences and what kind of experiences and make that visual?

**Comment by simison** [comment]
What do you think about using the same questions as we ask in experience form?

- [ ] Hosted by them
- [ ] I was their guest
- [ ] We've met

I've been thinking it can be useful to have this stored in separate table as "relation information", and just surface it across contacts/experiences.

We could also add other relation info there later on: "I live in same household", "we're same family", "we're couple"... and surface those contacts differently.

**Comment by noahsmindfuck** [comment]
Yes, I was thinking of that! Actually, I would say an _experience_ and a _contact_ are the same, they are just different angles to look at the same thing, different point of views. I was in contact with anyone I have an experience with and with every shared experience I experiences a certain level of contact.

So I basically advocate to merge them :D

**Comment by simison** [comment]
Yes'ish, except you'd really add contacts only as people you probably wanna keep in touch with. (my assumption anyway) It's useful as separate thing but I agree there's overlap.

**Comment by noahsmindfuck** [comment]
Well, it seams that it doesn't work that way,a t least not with those newcomers that view TR as a social network where the amount of contacts is basically like money ;) the more you have the better.
Even on my profile I receive regular contact requests from totally unrelated members :)

**Comment by hlibbabii** [comment]
> Yes'ish, except you'd really add contacts only as people you probably wanna keep in touch with. (my assumption anyway) It's useful as separate thing but I agree there's overlap.

Does it make sense to make contacts invisible to others then (is there overlap with bookmarked hosts here, btw)? Or we still want to try having it as a safety feature?

**Comment by simison** [comment]
It's very useful to have it public, for example to highlight common contacts between members. Folks are much more likely going to host folks with common friends (per my gut feel).

**Comment by simison** [comment]
@noahsmindfuck 

> Even on my profile I receive regular contact requests from totally unrelated members 

Yes, but that's a bit different compared to situation where you actually did meet someone, didn't have great experience, and want to write about the experience but not add them as contact.

E.g. I'd expect to see my contacts on map, but not expect all the people I've written experience about have on the map. I also wouldn't necessarily write experience about every friend I wanna add as a contact just because it's a lot of work.

**Comment by noahsmindfuck** [comment]
@simison 
exactly, that's why it does make sense to differentiate them. Maybe we can 'tag' people that we met/contacted/are experienced with/... with sth. and then you can show on your map ppl that you have tagged.

I think it is to static to have a feature that is like "show everything of <category X> without flexibility" where as if members can categorize themselfs they are able to design their own feature and their own experience.

So if you have an experience with someone or add as contact (for both) you would select the "relation" which has to be for trust measurment at least one of (public) 'have met'|'have never met'|'good vriend'|<necessary category> and can additionally receive individual (private) tags like 'emergency host'|'bff'|<category Y>

I don't know how much change that would be to the experience feature as it is designed now but I think this is where we should go.

**Comment by simison** [comment]
Oh at this point I'm counting most things as follow-up iterations, not something that should be done before the release unless absolutely must. ;-)

**Comment by MrSalami** [comment]
I am also beginning to get random contact requests now, the same way I did on Couchsurfing and have been telling those that I don't typically accept those who I don't know. I never accepted any contact I did on CS, which must have been at least 100 over the years. 

There is social value to get gained in adding people as contacts thus improving ones trustability, which may not actually be true. So I would support something to prevent the behavior from happening however that looks.

An additional suggestion would be to have a popup come up after the add contact was clicked and have the wording be " Do you actually know this person? We only recommend you add contacts of people you have met or had meaningful interaction with." Yes, someone can just ignore it and add anyway, but it could be a way as an organization how we are "trusting" the user to make that decision since we are a trust based network after all. 

On the flipside, when someone receives a contact request, a message can be said " XXX user sent you a contact request. We recommend you add only those you have interacted with personally to maintain the trust of the platform." or something like this. When a contact request is sent to that user, a message can be populated in their inbox.
