### ISSUE TITLE
phone number verification

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#211]
if we want to implement phone number verification, nexmo.com API can handle this

used nexmo for https://github.com/guaka/hitchticker/issues/2

**Comment by honzahosek** [comment]
1 verification costs €0.1, not very cheap.

All verification can be community based.
For example for phone numbers:
1. Website gives you phone number of highly trusted member (preferably from your country) who guaranties you response in 24 hours and your verification code.
2. You text her kind message including code you got with her number.
3. The highly trusted member punches the code and your number in form which is checked with your number.

The highly trusted could mark their availability for each kind of verification. I would be fine to do such job.

Address, identity, authenticity of photo, or important statements of the profile could be verified in similar ways. Lower level of verification could do guests to hosts, or other not (yet) highly trusted. 

All the trust records should be kept in database and could be used for overall networks trust computation.

Members should be asked to take their trust actions seriously and take responsibility for it.

**Comment by libertedeparole** [comment]
What is the purpose of verifying phone numbers? I've studied this question quite a bit concerning safety issues. I don't see it as a safety measure, but as a publicity measure, counterproductive to safety, which gives people a false sense of security. It is extremely easy to purchase unlimited cellphone telephone numbers.

**Comment by simison** [comment]
If we some day add phone numbers to the profiles AND want one day to build features around it, it's better to have verified numbers, just like with emails.

@honzahosek we can verify for free if we build the logic ourself, the cost is at sender's side.

@libertedeparole Verified phone number isn't much of a security feature, but there are other fun things to do with this stuff. :-)

This is more like a reminder that this stuff exists.

**Comment by guaka** [comment]
I actually do think a verified phone number can be part of a security
feature. There's a cost in getting a phone number and once we have a phone
number tied to a profile marked as bad the phone number can't be used again
for another profile.

**Comment by simison** [comment]
With something like 
>_"We've verified this number exists and is registered only once at Trustroots. However we can't ensure it really belongs to this person or if it's an anonymous prepaid number."_ 

next to it?

**Comment by libertedeparole** [comment]
On 13 avr. 2015, at 23:09, Mikael Korpela <notifications@github.com> wrote:

With something like

"We've verified this number exists and is registered only once at Trustroots. However we can't ensure it really belongs to this person or if it's an anonymous prepaid number."

next to it?


At least that reminds people it isn’t a safety measure.

I admit, I don’t understand the advantage of “verifying” (see below) a number works. 

At best, in an age when some people change numbers often, it “verifies" that it once worked. It verifies they didn’t make a mistake when typing the number - which does have a small advantage. It would be necessary to keep verifying every month to get anything more solid out of it, which would just be that it isn’t a non-working number.

In many countries (not all) one can anonymously and legally buy new cell phone numbers for less than 5€ in unlimited amounts at stores on every corner. 

But even with actual verified land lines with official billing, TR will have no access to the real name associated with the line. Only if police get involved will they (and they alone) perhaps trace down the information on the number, perhaps only to find that it is being used anonymously or fraudulently.

Perhaps it would at least be better to say “we tested the line is working”. Instead of using a word like “verified” that implies for most people something stronger than that an anonymous person answers the phone or receives an sms.

**Comment by libertedeparole** [comment]
Dino Magloi, was sentenced yesterday to 6+ years in prison for one of the hundred rapes police suspect him of performing using CS, most of which happened after he had been repeatedly reported to the CS safety team.

**Comment by simison** [comment]
@libertedeparole for any features that might be sending outbound messages, we'd want to have a verified number to avoid sending sms's to non-existing numbers.

Thanks for input.

**Comment by libertedeparole** [comment]
Thanks Mikael. So these would be telephone numbers that are not available to members? Or not defined as "verified" to members?

**Comment by libertedeparole** [comment]
If a member decides to make their telephone number publicly available, and a TR process found that it was not a working number, it would seem to have less negative safety impact to simply state something like "number reported not functioning April 2015", perhaps after informing the member.

**Comment by simison** [comment]
Actually, sorry @libertedeparole, but this isn't a feature on a todo list right now so let's not dive too much into details before anything would be more thought. 

In the future please note "milestones", if it's in a "long term future", it literally means that. :-) Also I don't wanna see too derailing discussions under each todo, unless it's an issue opened specifically for that. This thread already has a bunch loose strings under it so it becomes unclear what is even being discussed.

@guaka in the future if you want to save resources, examples or possible use scenarios, use Wiki instead of the todo list. Moved this to [here](https://github.com/Trustroots/trustroots/wiki/Services-and-resources) instead.

Aight, I recon we'll get back to this again a bit later.

**Comment by libertedeparole** [comment]
Guaka suggested exploring a specific tool for telephone verification. That is what I first responded to. It seems a waste of resources to explore tools if no verification is planned. On the other hand, when people invest in "solutions", there is a tendency to follow up. Guaka then defended the idea that telephone “verification” can be a useful safety tool, even apparently explaining that the prohibitive cost of an anonymous cellphone number would be dissuasive to wrongdoers, something I can’t believe he really finds to be true. 

I don’t think you really believe that considering safety on TR should be relegated to a “milestone” long term goal. A system that is not conceived for key concerns from inception will likely be unwieldy in addressing those goals. 

Perhaps there are few effective measures that can be taken for safety, short term or long term. Some actions are more dangerous than others. But claiming they are not dangerous, or that there are effective safety measures in place when there are not, only increases the danger.

At the same time, there is clear evidence that dangerous individuals are specifically targeting vulnerabilities in hospitality sites NOW. I don’t think anyone wants a TR Dino Maglio to be the first wake-up call.

My prime concern is that TR does not copy the CS model of giving people a false sense of safety that has been one part of what has led to hundreds of rapes on CS. In my opinion it is better to say you are doing nothing for safety rather than talking about “verification”. 

And if safety concerns are ever to be a real part of the TR system, that cannot be left for the long term future.

**Comment by simison** [comment]
Yea, true. CS indeed doesn't handle stuff very smartly. Someone put it well; "don't concentrate on building security features when you can build trust features".
