### ISSUE TITLE
"Hangouts" feature 

### ISSUE THREAD

**Issue by chagai95** [Trustroots/trustroots#2117]
**Is your feature request related to a problem? Please describe.**
Travellers are not visible while travelling. Trustroots is also about connecting like-minded travellers (for example the meet functionality) and it would be nice to be able to connect even more people. When trustrooters travel they are not visible at all because they have to change their status to not hosting which reduces general activity and there is already not much activity.

**Describe the solution you'd like**
A hangouts similar feature like Couchsurfing used to have. One idea would be to just have another category just like the meet category but for travellers and travellers could change it every time they change a city.

**Describe alternatives you've considered**
Relying on location on mobile would probably be really cool in the long term, but this is difficult to program and very controversial. 

**Additional context**
We got this request from two people who responded to the user survey:

> I would really really love it if the app showed the location of travellers whilst on the road. I would like to meet other travellers as well as hosts wherever I happen to be, but I can't see who is around the area at the time unless they live there and are at home. And I'd like people to be able to see when I'm visiting their area without changing my home location with every step along the road.

>Some sort of "hangout" feature like the couch surfing hangout, that would allow us to find or be found by nearby people who belong the same tribe could be interesting.

**Comment by annazi-maker** [comment]
I support this function in TR but having read discussion on this in reddit i add the following for your consideration.
1. Hang outs in CS app eats valuable cell battery so some travellers cannot use it at all
2. Is there a way to have a hangout functionality that is a bit different from that CS is using, like send notification if a TR member is nearby even if their cell connected to wifi/data only briefly (add a kilometers scanning tech on the TR app to tell you if another TR member is 1 km away / 2 km away / i dont know...10 km away max?)--> im not a techie so im not sure how easy is this for tech or if its really a good feature. But its an alternative to having a hang-out running live 24/7 as in CS which eats battery?
3. Safety: non-tr members cannot enter the hang -out and peole who made a profile 24 hours ago or 72 horus ago still cannot enter a hang out (a profile must be old enough to ensure that abusers dont contantly make accounts , do harm, insult , etc then get banned and make new account and rejoin hangouts).
4. If there is a discord chat channel (we are discussing it in the slack channel ), then if the blog/twitter/youtube of TR advertises regional chat channels in discord, could this be low tech/less bulky way to have ahang out function? If you travel to Hong Kong, you can enter the Hong-Kong Trustroots discord channel ? Thisis less techy and less tech-demanding but it requires an admit for each channel, therefore I assume its not feasible unless someone local is very active volunteer and really wants to get TR going in his/her area (some volunteers are like that) and they can  really help by having a blog about their area in relation to TR  events and be the moderators of a discord channel related to that area.
5. For old people Internet Relay Chat can be used but  people younger than 40 propably dont know what it is. Its less bulky than discord interface. Someone can connect with kiwiirc, or mibbit, or my favorite ircloud.  Irccloud (im not affiliated), may be approached by trustroots as a corporation to run regional channels and have bots (not humans) as admins of each channel? Im just tossing ideas ok dont take me very seriously:)
6. Events in couchsurfing worked better sometimes for me than hang-outs. Its more safe too (to my experience). Events have specific aims, specific venues, and are re-arranged. TR already has this function but i dont see many using it. Maybe send reminders to active members to remind them to create events even if its a chat in the regional or general TR discord channel (if that idea is realized, to have a discord channel that is). ?

**Comment by MrSalami** [comment]
I have never liked the hangouts feature in CS, and mostly because it attracts men only looking to hangout with attractive women. The women that do use it get contacted a lot and can get overwhelmed, and not made to feel safe and then leave. If you use hangouts on any city in Trustroots, (and I check it constantly wherever I go) it is mostly comprised of men. I have pinged these men, many times, to simply hangout, and I don't get any luck. But if a woman shows up, then she is getting hit up a lot .

I have made a connection with hangouts with a woman, who could be considered attractive, and everytime I do it (and she very well may trust me because I have over 170 positive references, as opposed to someone who has none) then there are several men who want to join our hangout. Sometimes I add them in, but they hyper focus on the girl and want to get drinks with her and ask her questions as opposed to being interested in me. 

On top of the safety issue and having hangouts being used a way to meet women, it has always sucked. The messages don't get received right away, and many times when I did hangout with someone, the message was not received, or they didn't get notified, and so if I ever did use it, I told the other user to go to whatsapp as soon as possible. 

It's not a great feature and think events are better for getting people together in groups.

**Comment by chagai95** [comment]
@MrSalami I agree that we need to take this into consideration but I don't agree we should not think about this as a feature just because couchsurfing messed it up.

Let's take this discussion to Slack whenever we actually have a developer ready to put time into this, otherwise we are turning GitHub into a forum...
