### ISSUE TITLE
CI setup

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#228]
- [ ] automatic deploy to dev.trustroots.org after push to master
- [x] set up Jenkins, CircleCI, Travis or something else _(using travis)_
- ...

**Comment by simison** [comment]
Added https://github.com/Trustroots/trustroots/blob/master/.travis.yml

**Comment by Frijol** [comment]
Just found Trustroots through Hitchwiki (one of my favorite sources for on-the-ground gritty travel info!). Looks cool, started checking out contribution needs.

I was directed to this issue from [https://github.com/Trustroots/trustroots/wiki/Development](https://github.com/Trustroots/trustroots/wiki/Development)

(this part of the page:

![screen shot 2018-01-27 at 5 13 07 pm](https://user-images.githubusercontent.com/454690/35477973-933d6ade-0385-11e8-8f08-e7153a4b1490.png)

)

Should it be removed from that readme?

It looks like you're set up with Travis, though if you're still soliciting opinions, I found CircleCI really easy to set up on a different project ;)

**Comment by simison** [comment]
oh yea I'm happy with the setup we have right now. Thanks for checking!
(closes #228)

There is plenty of other work to do, tho! Could I invite you to our slack?
Write me your email to mikael@ihminen.org


On 28 Jan 2018 03:16, "Kelsey" <notifications@github.com> wrote:

Just found Trustroots through Hitchwiki (one of my favorite sources for
on-the-ground gritty travel info!). Looks cool, started checking out
contribution needs.

I was directed to this issue from https://github.com/Trustroots/
trustroots/wiki/Development

(this part of the page:

[image: screen shot 2018-01-27 at 5 13 07 pm]
<https://user-images.githubusercontent.com/454690/35477973-933d6ade-0385-11e8-8f08-e7153a4b1490.png>

)

Should it be removed from that readme?

It looks like you're set up with Travis, though if you're still soliciting
opinions, I found CircleCI really easy to set up on a different project ;)

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/Trustroots/trustroots/issues/228#issuecomment-361029936>,
or mute the thread
