### ISSUE TITLE
Paginated message thread

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#231]
Paginated in infinite scroll for messages.

Now it just loads everything into one long thread. Bad esp. for mobile performance.

There is [Waypoints](https://github.com/zumba/angular-waypoints) in use at that scroll view, which you can probably use as a watcher to poll for new items. It's now used to flag unread messages as read.

Bunch of packages that should be checked:
https://github.com/expressjs/express-paginate
https://www.npmjs.com/package/mongoose-paginator
https://www.npmjs.com/package/mongoose-query-paginate
https://www.npmjs.com/package/mongoose-pagination
https://www.npmjs.com/package/paginate-for-mongoose

Front:
https://github.com/zumba/angular-waypoints (already there)
http://binarymuse.github.io/ngInfiniteScroll/

See also http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#pagination

**Comment by katsuroo** [comment]
I will work on this if no one else already started.

**Comment by simison** [comment]
Coolio! This has work at both, backend and frontend sides. Backend should be pretty straightforward (and I'd like to think that same solution should be generic enough to suit paginating other collections, too).

Lemme know if you need help with frontend stuff, messages controller is a beast right now. :-)

**Comment by katsuroo** [comment]
@simison Most of the work is done, but I find that the link header doesn't really work well for the current structure. I have to use regex to parse the link on the frontend to use it. Also $resource( or $http rather ) have does url entity encoding when you pass in a url to the factory function. The backend middleware doesn't seem to pick up the userID param properly when its encoded. I What I ended up having to do is inject the $resource into the controller and code the url directly on the object with a variable. Perhaps custom headers would be a more elegant solution? What do you think?

**Comment by simison** [comment]
Great to hear!

Yup, link header isn't that important.

I'd still pursue getting it work with Resource, so that everything stays more modular. Can you see is it passing the userId at all to the frontend? This bit intends to be tricky to understand with Angular-Resources: http://stackoverflow.com/questions/17559515/what-is-id-as-passed-to-resource

Could you push some code to your fork so that I could inline-comment there?

**Comment by katsuroo** [comment]
It is passing the userId. Yeah, I should probably clarify what I said a little bit. I don't plan on using the $resource in controller, I guess it was more of a test to see how $resource work than anything. Sorry for the confusion lol. I'm sure it will work if I breakdown the url with regex and pass in everything as param. 

I guess the whole point of my last posting was to ask whether you would like to stick with passing the url in the link header or break it down to key / value pairs. Since it doesn't seem like it would make much sense to stick to that convention when it only creates extra work.

 But now that I think about it again I guess I can probably just extract the userId and then append the rest of the url as one big query string to the resource.

The code is on my desktop, so I'll push it when I get home tonight.

**Comment by katsuroo** [comment]
@simison Did you have a chance look my commit? Let me know what you think. I think I just found a bug though... Seems the pagination method doesn't first if you scroll up really quickly after fetching the previous page. I'll look into that later. 

Also this snipet of code:
https://github.com/Trustroots/trustroots/blob/master/public/modules/messages/controllers/thread.client.controller.js#L82-L87

Is threadScrollBottom called 3 times to accommodate client latency during state change? I implemented the message calls to a promise , so perhaps we can have this first in the promise resolved? Right now it just calls it a few times when you switch into threads, which is kind of annoying.

**Comment by simison** [comment]
Hey! Sorry, I didn't yet check it. I've been busy on the road / with work meetings past week; I'll be back home tomorrow and I'll look into your code asap.

Yup, 3x thingy is a hack; although data is in the scope already, but if you had long lists of messages, it would take ages to render in the browser, thus the silly 3x thingy. Or was it really out of $promise as well? Bugger. :-)

Actually the whole messages resolver thing has to be moved to route config, something like this: https://medium.com/opinionated-angularjs/advanced-routing-and-resolves-a2fcbf874a1c

**Comment by simison** [comment]
BTW remember to test also with mobile; onScroll events are typically horribly unreliable with mobile browsers.

**Comment by katsuroo** [comment]
Yup, tested it on my iPhone. It actually works perfectly, the only problem was that it doesn't get the next page if I scroll really faster to the top on the desktop after the previous message digest cycle. 

But yeah, I'm experimenting with using a directive to trigger the pagination call instead of the waypoint method right now and it working perfectly. I'll do a little bit more testing and see how it goes.

We probably don't need the 3x thing, now that its paginated. I'm using a $timeout to delay my method till redraw for calculating new scroll height and it seems fine even though I didn't attach a delay for it. And it seems to be doing that fine consistently on my iphone as well as my desktop. So perhaps a default $timeout is suffice to push the execution after the digest cycle? Maybe we can get away with just calling it once in the resolved message call promise?

Oh, and let me know if there is anything else you want done on the message module,  now that I familiarized myself with it. Good luck with your work :)

**Comment by simison** [comment]
Sounds really good!

Looking at your code now.

You can do overall improvements for it if you can think of anything; esp. on mobile. See all the issues related to [messages module](https://github.com/Trustroots/trustroots/labels/Module%3AMessages).

**Comment by simison** [comment]
Added some inline-comments to https://github.com/katsuroo/trustroots/commit/55e5681bdece68e4d2b972f706f04617b40534c1#commitcomment-11128126

Good job!

**Comment by simison** [comment]
@katsuroo BTW make sure to merge with this commit;  https://github.com/Trustroots/trustroots/commit/5cf86b06252dfc6581abb29cff80456be13379c5

PS. I added you to Devs team, welcome! :-) :thumbsup: :beers:

**Comment by simison** [comment]
Merged https://github.com/Trustroots/trustroots/pull/267#event-307390834
