### ISSUE TITLE
Migrate out of Travis

### ISSUE THREAD

**Issue by wetneb** [Trustroots/trustroots#2389]
Thanks for running this very nice platform!
**Describe the bug**

It looks like Travis is no longer building pull requests or the master branch: according to https://travis-ci.com/Trustroots/trustroots, the last build was two months ago. This is probably because of the recent change of policy in Travis, which assigned a fixed amount of credits to OSS projects and stopped building them when those credits run out.

Do not be mislead by Travis' communication: they are basically closing down and do not have the capacity to support OSS projects anymore. This blog post explains it well: https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

I had the same problem in many repositories and have been migrating them slowly to different providers. It can be quite time consuming unfortunately. There is also the option to request additional credits to Travis so that PRs keep building for some time, but in my experience it took many months before they granted my request for OpenRefine, so I am glad I migrated to something else earlier.

**To Reproduce**
1. Open a PR
2. See it does not get built

**Expected behavior**
The CI should run.

**Additional context**

There are other free CI providers: GitLab Pipelines, GitHub Actions, CircleCI, and probably many I am not aware of.

**Comment by mariha** [comment]
I was planning to migrate it to CircleCI to avoid any potential vendor lock-in and in case TR or [OHN](openhospitality.network) (what we've actually discussed) wanted to move to other forge, like gitea (which last time I checked was not currently supported by CircleCI either, but I guess it has greater chance to be then any other mentioned, I'd hope for the best and give it a try). 

But if anyone else would like to take it, go for it!

**Comment by simison** [comment]
Thanks for outlining this! Yeah sucha bummer with Travis!

CircleCI or GitHub actions both (or some combination) work for me personally. I have good and poor experiences with both. :-) Help to write a config most welcome! Ping me on slack for access/accounts on anything you'd need.

For basic CI needs we have such small and simple needs that I'm not personally concerned what to use or that we'd get locked on anything, or spend too much time comparing alternatives, because effort of rewrite is so low. I'd just pick something and move on.

Continuous delivery pipeline is a different matter tho (we've had autodeploys to a beta server on merge) and its quite a bit more to move around. I'm not sure what's the best direction for it. In interim might make sense to not have it and prioritise fixing CI setup.

Based on experience on TR and elsewhere, a system which allows testing the PR in temporary manner seems most impactful instead of beta server. It's usually what drives the same purpose beta server is used, and more.

Anyhoo, maybe simple CI first up... 🙂

**Comment by wetneb** [comment]
I don't think I am in a good position to work on this, not having any experience with Trustroots as a developer, so the floor is yours :)

**Comment by karlkeefer** [comment]
Cool 😎 will have to give Actions a closer look!

**Comment by TMC89** [comment]
Is someone working on this last point at the moment: **Beta deploys**?
