### ISSUE TITLE
Nudge about sticking to exchanging messaging on Trustroots

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#2495]
_This is a summary of the conversation within the safety team (myself, @loberto, @LudoB8)._

Our support team has a way easier time dealing with abuse when there's a record trail on our side, instead of external messaging apps like Whatsapp.

For example:

> He asked to keep on our conversation on WhatsApp and then he showed me his pen**s.

This example is straightforward, but now we're relying on screenshots we need to trust are not faked. And usually issues are much more nuanced than that and neither party is really telling the truth.

It would be helpful to make this clearer for members in the UI; we can't control what people use, nor what people write, but we can make them aware of risks. There are legitimate uses for external apps especially closer to time to actually meeting/coordinating with people, or last-minute hosting requests, but I think it would be fair to discourage at least for initial message exchanges. Even if people feel confident and they’re not bad-doers or anything, they’re still setting up a culture of using WhatsApp over internal messaging.

We could show some kind of alert under profile description and messages when people mention “whatsapp”, “telegram” and such:

<img width="686" alt="Screenshot 2021-12-15 at 21 03 20" src="https://user-images.githubusercontent.com/87168/146249097-464d5f84-3182-4fc5-8d07-0d81a150f91e.png">

<img width="619" alt="Screenshot 2021-12-15 at 21 04 42" src="https://user-images.githubusercontent.com/87168/146249094-696ed29f-40f9-48fd-9fed-175125d9b9f1.png">

**Comment by chagai95** [comment]
I'm gonna say this first so it's clear:

I have some strong opinions about this and I'd like to express then in a free way, please don't take anything personally and I mean it all with a lot of love because I'm passionate about connecting people and making this a great platform 🥰🥰🥰🥰

So here goes:

Such a warning triggers me straight away and reminds me of apps that like vendor locking, Couchsurfing being one of them. They used this exact same argument as an excuse to block people (safety argument to stay on their platform).

when we say Whatsapp/Telegram here it can also be Email/Matrix/Signal and whatever and I think we should definitely support an open culture of "use whatever you want".

I understand the need for safety, and I can see why it's extremely important, I don't think that our support channel is the solution. The best we can do in my opinion is warn people as much as possible that there are creeps and thieves out there. I don't think we can do much more than that. Of course we can block people but they'll just make a new account so I can see how it's tempting to think we solved the problem but I think we'd just be giving people a fake feeling that there problem is solved. People should go to the police, to the news and to social media to out such creeps they shouldn't go to support. If they come to support we should tell them that we're useless and that they should go to the police, the news and social media. After that we can then go ahead and block the other person's account and maybe even send a message to all of their contracts on Trustroots but that's just an extra and it doesn't mean a lot.


The complexity that is being brought into the platform in the name of safety is huge - a whole messaging system, a support team, people having problems with contacting other people because notifications don't work and much more is for me a very sad story.

I proposed adding a jitsi look to encourage safety and the experiences also adds a layer of safety (I think it can backfire but that's another topic) but I'm definitely against this...

So to summarize:
I'm against this from a moral perspective because I don't think our job here is mainly connecting people as a platform and not pretending we can keep them see l safe and also from a technical aspect I think it's a disaster for the platform to keep on trying to hang on in a battle we lost long ago, most people (I'm guessing) will move to Whatsapp as soon as they have a chance to and we shouldn't try to prolong the inevitable, those other apps also gave safety features and they should deal with safety issues, we should be happy people found each other on Trustroots and let them communicate however they want...



Would be happy to jump in to a call with anyone about this, when I write it sounds worst than when I speak so sorry 🙈🙈 hope I didn't get anyone need 🥰😊🥰😊🥰

Https://chagai.website if you wanna talk...

**Comment by loberto** [comment]
You guys need to stop thinking that I am taking this personally... it's just different viewpoints.

If I understand Chagai correctly: in the extreme, your solution would be to close the messaging system in TR completely, and only use external messaging services. --> I am not completely against this, if this is the official stand we have on TR.

However, if we keep an internal messaging system working, it MUST be the main form of communication we encourage. Because people WILL ask Support for help.

---> and reply to specific point by Chagai :
- the specific "warning sign" that we want is, as you even said, a warning... in difference to CS, we allow people to "use whatever you want", but the warning is to say "we will have no record of the conversation"
- 
-  In this comment:
> If they do come to support, we should give them a lot of mental support, tell them that we're useless technically and that they should go to the police, the news and social media
  - the Support tema is NOT there to give mental support. we are not therapist or health workers. so this is a **BIG NO**.
  - depending on social media may seem to you good, but for me is a huge pile of potential problems. most importantly, what can a user on the other end of the world do to help a person having been harrased in one town in europe? 
  - banning, suspending, contacting the reported User, this are all tools that the Support team can use. and even if user can create a new profile right away, it takes time and effort... and a brand new profile is not as trustworthy as an old one. and with the Experiences being used, older profile will generate more trust also.
  
 ------------------------------
 summary:
 - if TR has a messaging system, we have to use it and encourage people to stay on it.
 - if TR will encourage use of external messaging systems, then we should simply kill the internal one and be done with it.
 
 the middle ground is unnecesary.

**Comment by chagai95** [comment]
Hey, thx for replying.

I prefer not to get into a discussion in writing about this so I'll keep it short, could you help me understand the following?

1. How helpful it it for the abused person when the abuser is blocked? Could you give some use cases?
2. Why can we not have messaging on the platform and also promote people to use whatever they prefer?
3. How many cases are there now, where users actually only use internal communication? Do you have support cases where you can see that? Do you think we can convince everyone to actually stay on the platform?


I agree to some extent that we provide some sort of safety and experiences are going to help with this.

**Comment by simison** [comment]
Let's not dwell on the fundamentals of supporting our members vs intentionally not supporting, or about blocking people vs letting people be, and such. It's a way too wide topic for a Github thread like this and thus unlikely to be very productive or actionable. We can bring this topic to discuss with all of the support team in a separate meeting if we have an appetite to continue the convo.

This thread is an excellent spot to discuss cons/pros of nudging about the external messaging though.

**Comment by loberto** [comment]
so my opinion is clear: we can allow people to use whichever communication method they prefer. And we should give a clear message that the Support team recommends staying on the in-app messaging system as much as possible, to be able to keep track of the conversation in case on any issues.

**Comment by xeruf** [comment]
This would be a lot less of an issue if the messaging used XMPP, thus supporting many apps across many platforms, making the roundtrip via extra apps superfluous...
