### ISSUE TITLE
Remove the time/amount limit of how many people you can write in one go

### ISSUE THREAD

**Issue by chagai95** [Trustroots/trustroots#2503]
I think it is important to fight spam somehow, but this is imho an anti-feature that bothers the user a lot.

Why?

1. You can not write messages to people even if you already had a conversation with them before, because you reached the limit, this seriously hurts communication.
2. Many people are not active at all and you end up writing messages to many people who don't answer, so it is actually crucial to write as many people as possible to find at least one host.

Here is me getting stuck with this, this has happened to me countless times (also on Couchsurfing) amd I've heard from others that it's extremely difficult to find a host like this:
https://youtu.be/naX9N_cAPnk?t=1489

Alternatives:

1. Add a public trip feature https://github.com/Trustroots/trustroots/issues/2405
2. I'm open for more ideas...

If you (Trustroots team) are not convinced, please at least consider:
1. bumping up this amount limit 
2. bump down the time limit, so you can write again as soon as possible. 
3. Make it possible to write people who already answered you.

**Comment by simison** [comment]
Thanks for elaborating! Rather than "let's remove this is bad", let's acknowledge that this isn't gonna be spot on adjusted at first attempt — not even on second, and let's tweak it to find right setting that doesn't annoy real people but is still effective in fighting spam. It's not gonna be only mechanism we need but it's one of the easier ones.

All 1—3 are important to keep adjusting; 3 is more work but definetely a good idea. 1-2 are easily adjusted technically but finding a good limit is harder. That's why we collect stats on this (see grafana) and we can look into each case catched to see if it was spam or not and what limit they hit.

**Comment by chagai95** [comment]
Ok thanks for answering so quickly as usual 😉 

I'd be interested in more arguments as to why Spam is worse 🙈

I think not being able to find a host because of these limitations is a huge issue which will be the reason why many people don't use the platform, so I'd advocate for as less Spam fighting as possible if it results in this even though that'll be very annoying for many people at least others can find hosts...

Maybe some more low hanging fruits:

1. Warn the users how many messages they have left so they can plan who they prefer to send a message to - warning after 20 and block for 2 minutes after 30 then completely block after 35, or something of the sort?
2. Make it more clear after how much time this limitation will be lifted.
3. Warn spammers more about the consequence of spamming - legal implications, maybe actually sue these people, who are they? I don't think these are bots? Am I wrong?


I'm very much interested in any other alternatives or discussions, maybe we can find an interesting and creative way to solve this, how to other websites fight this?

**Comment by chagai95** [comment]
Thanks for pointing at the statistics, I'm really bad with understating statistics so I'll leave that for other people but I think it's a great point!

Thanks also for making it clear that Spam is auch a difficult issue, I might have exaggerated a little bit because I noticed that actually after a little bit of time I could easily write some more messages but I still think this is a bad idea because I think we should me encouraging people to send many messages otherwise they won't find a host and in general I'm assuming (no statistics 😉) that most people will be afraid and not send many messages after seeing such a message or they will not come back to the platform for a second round...

**Comment by Daucus-gh** [comment]
leaving a limit also when replying to someone that has already contacted you (not necessarily that has answered !) is something that makes the whole platform not viable.
Think about someone that has received 50 request on the same day, because it would live in a place when at a certain time [a contert ? a summit ? a big event ] all he world want to go there. It would be willing to accept only certain people, but giving the limit on the number of replies, even if willing to tell no to people that would refure, would risk to finish the daily allowance before having answered to everyone. [real case: in 2016 for the 30th of april in my city where on the same day two concerts with an huge attendance both at 2030-0030 but one in an arena 10 minutes walk from my home, the other in another one, 50 minutes by bus (plus 10 walking to my home); I got about 30 requests [on CS and BW], mostly from people going to the second one, that I dropped immediately since they would not have been home before 2 in the morning, something i did not want, accepting only the two that were coming for the first one were accepted]. 
or think someone that has sent all its allowance to get hosted two weeks ahead, and receives a request to stay for the next day ...
Also, not all people has the same sensitivity to spam, and care more not to risk to lose possible valuable messages than having to manually delete bad ones.
A good idea would be then to allow people to mark themselves as "not strict on number of messages replied " and tag them is searches wit a symbol telling "messages sent to this person do not count against your daily allowance".
