### ISSUE TITLE
Link BW prefix isn't in use anymore

### ISSUE THREAD

**Issue by TMC89** [Trustroots/trustroots#2537]
From support:

> There is a tiny bug on the website (possibly on the app too): The link for Bewelcome uses a "www" prefix and apparently Bewelcome no longer use it so when people are clicking on the link it sends them the login page (even when they're already logged in). removing the "www" prefix solves it.

**Comment by rishav-karanjit** [comment]
@TMC89 Where is this issue?

**Comment by TMC89** [comment]
![Screenshot 2022-03-19 at 15 31 23](https://user-images.githubusercontent.com/74301087/159125211-4bbe4db6-e5da-4d78-91a7-3e5d78ec32c5.png)
I think they mean this connection, on someone's profile. But I just tested on my profile with a Safari and Chrome browser and everything seems to work fine..

**Comment by carez** [comment]
I had a quick look at Bewelcome and it works both with and without `www` (note that some browsers may hide the www, even though the actual URL is still using it. Make sure you use debugging tools or something that shows the actual URL).

The problem they seem to have is that their login cookies for each domain are independent. That is, you can login separately to either of the two domains, and being logged-in in one does **not** log you in in the other.

This confirms the problem in the original report. Anybody logged in in `bewelcome.org` will follow TR links that use `www.bewelcome.org` and, instead of landing in a user profile, will get redirected to the login page because they do not have login cookies for the `www` domain.
However, this is IMO a problem in the Bewelcome configuration, they should probably have a canonical domain rather than allowing both. If Trustroots were to start using `bewelcome.org`, we would fix the issue for users logged in there, but introduce the issue for users logged in in the other domain.

I tried to find out if one of the two looked "more canonical", but I could not find a clear indication. For example, the main logo seems to use both, simply respecting the one you started browsing. For what is worth, a Google search returns the one with `www`.

**Comment by simison** [comment]
:wave: @thisismeonmounteverest hi! You might wanna look into the hosting config at BW, see the above comment. :-) Hope this helps!
