### ISSUE TITLE
Not recieving e-mail confirmation

### ISSUE THREAD

**Issue by mgorskiii** [Trustroots/trustroots#2575]
Hello, I tried to sign up for Trustroots some days ago. I did my profile and the only thing missing was receiving an email from Trustroots to complete my registration in order to be able to look for hosts. I have tried with various emails and I have tried contacting trustroots support team through their website, email, facebook and now this blog. If anyone can help me, that would be amazing. Thank you in advance, Maciej

**Comment by xeruf** [comment]
Similar issue, not receiving any email regarding changing my mailing address :c

**Comment by belamu** [comment]
I haven't received any e-mails about incoming messages since about beginning of June as well.

**Comment by mariha** [comment]
@mgorskiii @xeruf @belamu it should be fixed by now. We had to setup new sparkpost account to fix the issue. Next TR newsletter will provide more background to this.

Some of the messages might have been lost. If you didn't get the message or the confirmation link expired, please request a new one to be sent in your profile page. Let us know if it works!

**Comment by belamu** [comment]
Yes, it is fixed for a while already now. Thank you!
