### ISSUE TITLE
Experience summary is reversed and confusing

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#2593]
This is from feedback from Trustroots support (Thank you!) ❤️ 

### Host and Guest summary is reversed

In this example, notice that the experience receiver was a host, but the summary said `Was hosted by 33% of members. Met with everyone.`
![image](https://user-images.githubusercontent.com/7449720/189670665-ec16492a-872e-4018-9932-90ad00af77e6.png)

### "Met in person" is confusing

In this example, it says `Did not meet with anyone.`, which is obviously not true. People giving the reference forgot to select or didn't understand the `Met in person` option (8 times!)
![image](https://user-images.githubusercontent.com/7449720/189669705-5cd5a227-4d3b-4e14-b935-f8c9c6aaba03.png)

## Reproduce

It may take a bit of searching around to find a profile with 2+ experiences in production. For privacy reasons we won't share usernames here. (Think which of your contacts may have done some hosting or guesting recently)

**Comment by mrkvon-tr** [comment]
Mentioned in https://github.com/Trustroots/trustroots/issues/2530#issuecomment-1213350521

**Comment by Iizuki** [comment]
It's still reversed.

It doesn't seem to come up that often as many users are 100% hosts or guests, or exactly 50/50, but here's one example:

<img width="866" height="1247" alt="Image" src="https://github.com/user-attachments/assets/69d0ff7c-32d6-40dd-83a1-cc8a945ba8d3" />

This user did host twice, but the text shows 0%, which is their *guest percentage.*


I think the issue is [here](https://github.com/Trustroots/trustroots/blob/4ba05057cb008dc2c9c7dedfcb8abf52f02bd7b2/modules/experiences/client/components/read-experiences/ExperienceCounts.js#L117-L135) where one percentage is considered in the if statements, but then another is put to the output string.
