### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#2595]
It's not great that Google is getting a lot of data about Trustroots users.

Moreover there may be legal issues:
- https://blog.didomi.io/en/is-google-analytics-illegal-in-europe-heres-what-you-need-to-know
- https://techstory.in/eu-declares-google-analytics-illegal-heres-why/

Of course most websites still use Google Analytics anyway.

What's the easiest way to disable Google Analytics on Trustroots?

**Comment by robokow** [comment]
``` $ trustroots/config/env/local.js```
Change line 229 to false 
or simply comment out line 228-231.

It's also in docs.
``` $trustroots/docs/_config.yml```

@guaka

**Comment by mrkvon** [comment]
I noticed through a link in Trustroots slack #log that issue [#2590](https://github.com/Trustroots/trustroots/issues/2590) with the same name was deleted (doesn't show who deleted it). Could we close issues instead, for transparency reasons? ❤️
I don't think we have any agreement on this. But i wanted to know what was there, and the `This issue has been deleted.` surprised me a bunch... 🤷🏾‍♀️

**Comment by mrkvon** [comment]
@anm created the same issue in #2590 (now deleted), and posted:

> Trustroots should not be compromising people's privacy in this way. It is also illegal in Europe.

If that's the case, this would be worth marking as high priority

**Comment by mrkvon** [comment]
@chmac Why did you delete my comment?

**Comment by mrkvon** [comment]
Just to clarify, it was a comment about https://github.com/Trustroots/trustroots/issues/2590, which was about google analytics as well, and in which @anm wrote:

> Trustroots should not be compromising people's privacy in this way. It is also illegal in Europe.

And i added: If it is true, we should make this a high priority.

I think this is a completely non-controversial comment, which is relevant in this conversation and which anybody is free to disagree with, but NOT UNILATERALLY DELETE WITHOUT EXPLANATION. (caps intentional)

**Please DO NOT remove this comment, unless you engage in a discussion. Censorship is very very much NOT OK.**

**Comment by robokow** [comment]
> I would also like to know why my issue and @mrkvon's comment quoting it were deleted. @guaka rewrote my issue and posted this one, while deleting what I wrote and referring me to the code of conduct, in which I could not find anything relevant.

Thank you for opening the original issue @anm. It's an important issue. Though, your original issue was not descriptive enough. Therefore, a new issue was created to reflect that. The point is the issue itself, and a clear description of that issue. 

A discussion about issues inside issues is also off-topic to the issue itself. I don't see why anyone would have an issue about that. Please let me know personally if you do have an issue about it, so we can have a talk about it, and keep this issue focused on the issue.

**Comment by mrkvon** [comment]
@robokow with all the respect, that's not what happened. @anm 's issue was definitely enough for a comment, and that's what my [original deleted comment](https://github.com/Trustroots/trustroots/issues/2595#event-7408898900) here was. A mere repetition of it, with a little bit of context. Very on topic. The current digression is a direct consequence of those deletions. I can't prove it, since it's deleted, but maybe other folks have the contents in their inbox as a notification...

In any case, there are better ways to deal with issues or comments that are too brief. Close it, or ask for expanding it, or expand it yourself.

Let's be clear here. Deleting uncomfortable comments is not helpful and it stinks of censorship and silencing. 💩 

We can do better than that. We can hold people accountable for their actions, and we'll all be better off in the long term

@anm i suggest you copy your original issue as a separate comment here and hopefully that will end the endless "mark as spam" and such comment will hopefully stay intact.

**Comment by guaka** [comment]
> I would also like to know why my issue and @mrkvon's comment quoting it were deleted. @guaka rewrote my issue and posted this one, while deleting what I wrote and referring me to the code of conduct, in which I could not find anything relevant.

"Examples of behavior that contributes to creating a positive environment include:
* Using welcoming and inclusive language"

**Comment by guaka** [comment]
Google Analytics no more
