### ISSUE TITLE
clean up .github/workflows

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#2677]
https://github.com/Trustroots/trustroots/tree/master/.github/workflows

Both lint.yml and test.yml don't seem to work as intended. Guess we can just remove them?

**Comment by chmac** [comment]
The failure is on dependency install. They worked fine last month:
https://github.com/Trustroots/trustroots/actions/workflows/lint.yml

I think they are okay, I don't see any advantage to removing them. I already removed one that extracted the translation strings because it was dependent on some SSH key or something. We can run that process manually instead.
