### ISSUE TITLE
general link to settings page

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#303]
Now settings are at https://www.trustroots.org/profile/USERNAME/settings

it would be nice to just have https://www.trustroots.org/settings - like that we could link to e.g. "Download your data" from https://github.com/platschi/trustroots/blob/master/modules/pages/client/views/privacy.client.view.html

**Comment by simison** [comment]
Same issue with profile editing:

https://www.trustroots.org/profile/USERNAME/edit
https://www.trustroots.org/profile/USERNAME/settings

Just so that it looks more logical when you're first at
https://www.trustroots.org/profile/USERNAME

Should we just remove the username from there or do a redirect? This works:
https://www.trustroots.org/profile/me/settings 
(since it ignores the username anyway and usernames can't be that short)

**Comment by simison** [comment]
Done with https://github.com/Trustroots/trustroots/commit/2d659fbcefdf3f3907a10405480af18979f23ac2
