### ISSUE TITLE
Trailing slash breaks url

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#323]
https://trustroots.org/profile/:someusername is ok, but
https://trustroots.org/profile/:someusername/ leads to 404 not exist.
the same with /search vs. /search/ and other urls.
Maybe it's by design, but it is confusing, i.e. when one writes a link from one's (human) memory and adds the slash accidentally (happened already).
I'm not sure about best practices/standards for this, but enabling it or (permanent?) redirect would be cool.

fast research:
possible fix: http://stackoverflow.com/questions/13442377/redirect-all-trailing-slashes-gloablly-in-express
some fun with redirecting and trailing slashes: http://expressjs.com/en/api.html#res.redirect
[and some article] (http://googlewebmastercentral.blogspot.pt/2010/04/to-slash-or-not-to-slash.html) etc.

**Comment by simison** [comment]
Thanks. Totally should work.

Since URL stuff is mostly happening at client side (not at Express), I don't think we can easily create 301 redirects for these.

We're using Angular [ui-router](https://github.com/angular-ui/ui-router).

Here's the config for `users` module (every module has its own config file):

https://github.com/Trustroots/trustroots/blob/master/modules/users/client/config/users.client.routes.js#L41

And here seems to be the solution: https://github.com/angular-ui/ui-router/issues/50 (towards the end of the thread)

**Comment by mrkvon** [comment]
That last link with solution has reference to this: https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-make-a-trailing-slash-optional-for-all-routes

>Set strictMode to false in your config block:
>```javascript
>$urlMatcherFactoryProvider.strictMode(false)
>```

Don't have any experience with MEAN or Angular. I wonder whether there is any place where angular.js can be configured globally (maybe [here] (https://github.com/Trustroots/trustroots/blob/master/modules/core/client/config/core.client.routes.js)?) to something like this:
```javascript
angular.config(function ($urlMatcherFactoryProvider) {
    $urlMatcherFactoryProvider.strictMode(false);
});
```
Otherwise it would have to be configured in the individual modules (which is not very [DRY] (https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)).
Didn't manage to install trustroots locally today. Otherwise would test it.

**Comment by simison** [comment]
Cool. I'll test that out at some point. That would go here https://github.com/Trustroots/trustroots/blob/master/modules/core/client/app/init.js#L15

**Comment by simison** [comment]
Finally works: https://www.trustroots.org/statistics/
