### ISSUE TITLE
Fix `npm run test:server:watch` task

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#429]
Works on first run, but when editing test files, fails with error: `TypeError: Path must be a string. Received undefined`

**Comment by mleanos** [comment]
This can be fixed by adding the `file` to [this call](https://github.com/Trustroots/trustroots/blob/master/gulpfile.js#L175). I verified that this solves this error when applied to the MEANJS project.

However, while fixing this I noticed this task seems to have other issues. For instance, some of the tests fail during the second run, whereas they passed on the first run. I'll open up an issue in the meanjs repo for what I'm experiencing and provide more details. I just thought I'd get feedback here to see if anyone else has experienced issues with this task since it appears this task is being used by users of this project.

**Comment by simison** [comment]
Hey! Thanks for looking into this @mleanos.
