### ISSUE TITLE
add mastodon for social networks

### ISSUE THREAD

**Issue by b3yond** [Trustroots/trustroots#511]
Hey :)

mastodon is a new decentralised social network, where lots of people try to escape centralised services like twitter or facebook. I bet that the intersection between the trustroots.org and mastodon-community are pretty high.
You could maybe add the possibility to connect your mastodon profile with trustroots.org :) would be something for a short hackathon, I think.

**Comment by simison** [comment]
Hey! Thanks, I appreciate you reaching out. Yup, I've been following it.

Let's wait for a while to see if it actually catches on and if people start building social history there (because otherwise it's kinda useless to link to anything like that).

Do add a link to your Mastodon profile in your TR profile description and we'll follow up how many people do that and react accordingly when the time is ready for it.
