### ISSUE TITLE
Bad email checking in sing up page

### ISSUE THREAD

**Issue by AlexandrTsvetkov** [Trustroots/trustroots#524]
I am going to join the waiting list, but when I type my email in the input area and press the `Join Waiting List` button, I receive message like in picture below. It is trying to replace domain of my email to another domain.
![image](https://user-images.githubusercontent.com/6397482/27449493-e83252b0-5788-11e7-80fb-2bd8f1bd06f8.png)

**Comment by simison** [comment]
Hi!

You can just click "cancel" and it won't change your email. 

It's a feature from the service provider we use for the waiting list. It just asks if you really meant what you meant, since there's just two letter difference it checks you didn't do a typo (it would also ask for `example@gmaik.com` or `example@hoymail.com`

Thanks for taking time to report here!

**Comment by simison** [comment]
@AlexandrTsvetkov I meant press "OK" instead of course! ;-D
