### ISSUE TITLE
Extend tribes for wiki feature

### ISSUE THREAD

**Issue by jangorecki** [Trustroots/trustroots#552]
Sorry if it doesn't fit to github but I don't know better place to post it. Just an idea, not sure if not duplicate already, to extend functionality of tribes. We could integrate hitchwiki and possibly other wiki websites into trustroots platform. Basically there could be topics like on a wiki website. Depends on the tribes of a reader expected content is shown. For example, if reader of a topic about a city is a hitchhiker, busker and vegetarian he/she will see information related to those tribes... how to get out from the city, where are some vegetarian places to eat, where it is best to do busking or legal info related to busking. The same would applies to other topic that can be found on wiki like countries.

**Comment by simison** [comment]
Thanks! No worries, posting here is okay, typically it's better to send us ideas via [support page](https://www.trustroots.org/support) as here we tend to keep track of work rather than ideas.

Thanks for the idea.

There might be time when we'll look into extending tribes feature into new directions, but right now it's too early for us to expand to new areas outside just trying to get people meet and host and focusing on that.

Meanwhile we're better making Nomadwiki.org / Hitchwiki.org / Trashwiki.org / veganwiki.info better. :-)
