### ISSUE TITLE
Mark last minute requests as no longer required

### ISSUE THREAD

**Issue by chreekat** [Trustroots/trustroots#571]
After sending a flood of last-minute requests, I feel bad leaving all the still-unanswered requests dangling after I do finally get a place to stay. On the other hand, it's hard to go through all of them and manually update.

Steps?:

* Mark requests as 'last-minute' during creation (manually or heuristically)
* Provide 'cancel all last-minute requests' feature

or (more simply)

* Provide 'cancel all open requests' feature

or

* Pick multiple and mark canceled

All of this could potentially be viewed as rude/ungrateful depending on how the recipient gets the message. Maybe just a small text  in the message window, "Update: \<So-and-so> reports that they have found a place to stay in \<your city>, but I am sure they would still like to hear from you or meet up". Okay, that's a bit much, but something along those lines.

**Comment by trmendes** [comment]
I think it is a good idea to notify the user who got a request why is a specific request is not there anymore. 

I would like to have something like this:

* If the user who made the request (one or more of it) cancel it that user should wirte a reason why the requests are being canceled.
* If the user who made the request got a place to stay the system auto cancel all the other requests and tell those users the request is now invalid because the user who made it got a positive response already.
