### ISSUE TITLE
not receiving any emails from trustroots

### ISSUE THREAD

**Issue by albjeremias** [Trustroots/trustroots#577]
Hi,
I invited 2 friends to trustroots and they didn't receive any confirmation email, after registering.. And when clicking on forgotten password, i wont receive any email

**Comment by matt-and-cici** [comment]
Hello, we I have the same issue. I have created a profile from an invitation we got from our friend. Everything has been completed, but we cannot look for hosts since we need to receive an email from trustroots to do so. We have sent various email confirmations to our email and we got no answer. We checked our Junk Mail as well. We tried with other emails but still no luck. We also contacted them through the website in two occasions but we never got a reply and we also contacted them through Facebook. Let us know if you get an answer. Thanks

**Comment by simison** [comment]
Emails are rolling again.

Sorry for the trouble folks and thanks for the patience! We've had server issues and I've been on the road for the past weeks. All good now 👌 and looking into what to improve for this not happen again. I'm adding one more person who can help when server goes south if others are on the road.

**Comment by netdelight** [comment]
I used to receive an e-mail notification when I received a new message (which is convenient when somebody wants to be hosted) but it haven't been working for the past month. Today I've received the notifications that where sent 22 days ago but still not all of them. Is it a server problem or is it something wrong with my account ?
It's an important feature, can you confirm that it has been resolved ?
