### ISSUE TITLE
No notifications received

### ISSUE THREAD

**Issue by djahnie** [Trustroots/trustroots#582]
Three days ago I ([djahnie](https://www.trustroots.org/profile/djahnie)) asked _(removed private content)_ to host me in Lund, Sweden. He did not receive a notification. When he answered me after I contacted him via facebook I also did not receive a notification. No facebook notification and no email.

If we're not the only ones having this problem, then it's _really bad_! Please, please someone fix this!

**Comment by mgoonde** [comment]
Today I've received an email notification for a message that was sent to me exactly one month ago.
It's a bit annoying.

**Comment by netdelight** [comment]
Same thing here. And [not the first time](https://github.com/Trustroots/trustroots/issues/577).
Solving this should be a priority. Trustroots cannot work if the people in the community cannot be contacted in due time.

**Comment by fanaf** [comment]
Same problem here. I (and my partner who has a different account) didn´t receive in time the last 2-3 requests. When I asked to have my email account checked, the confirmation mail arrived a week later.
We are using Protonmail, but since this seems to be an extensive issue, I guess it´s not from our mailbox´s side.
