### ISSUE TITLE
Waiting list registration not accepting valid emails

### ISSUE THREAD

**Issue by eyalroz** [Trustroots/trustroots#586]
I just tried adding my email to the TrustRoots "waiting list". My address is eyalroz@technion.ac.il (the Technion is my alma mater university, and it's in Israel). So, first I got a dialog suggesting I meant 'ac.uk". Well, no, and this is already a bug. But when I insisted, I was told "email address invalid".

**Comment by eyalroz** [comment]
Update: A few minutes ago I got a "Trustroots Waiting List - Confirm your email" message, so maybe my email _was_ accepted despite the message saying it was invalid; in that case it's just the confusing suggestion and message that are the problem.

**Comment by simison** [comment]
Since this is a bug in an external system and it's already been a while, I'm going to close. Thanks for reporting it though and happy you could register after all!

**Comment by eyalroz** [comment]
While this might involve an external system, this is a bug with your system. It's the TrustRoots website that says my email is invalid.

Also, I don't see why the fact that it's been a while has any bearing. The website tells some people they can't sign up since it doesn't like their email addresses.

**Comment by simison** [comment]
@eyalroz thanks, yeah, I understand it's a bit frustrating. 

I'm not concerned because I haven't heard other reports from this (seems to affect only `.ac.il` domains which are a very small portion of our signups (albeit as important as everyone else!) and it didn't block the signup process, only caused confusion. That's not ideal of course but gives us an indication of priority compared to other tasks.

Finally, because this is in an external system we don't really have any _action items_ so there isn't much point for us to track it here at Trustroot's issue tracker. I've reported this to upstream so I hope it gets fixed there if it hasn't already. 🤞
