### ISSUE TITLE
Update language around meet -form

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#600]
Received feedback:

>it would be cool if the "meet" feature allowed for a specific time and address. I wanted to invite people to play board games today, but I wasn't sure how it would appear to other people when I set the date. 
>
>The use of the word "until" sounds like no one will see my post if I use today's date, but that wouldn't make sense. I think using the word "through" would be clearer. I was only able to enter the town name for the address, I'd prefer to be able to use a specific meeting point.

**Comment by trmendes** [comment]
I would like to work on this issue. I'm new to JS and I would love to practice while helping a project like trustroots.

I was checking the code here and it seems like the string comes from the template (offer-meet-edit-client.view.html). Since I haven't started to study Angular/React or any of the frontendian tools/frameworks I'm here wondering how does it works with the translation here?

**Comment by simison** [comment]
Hey @trmendes  :wave: Great :-)

We don't have translations at Trustroots so it's just a matter of updating the text from the template that you already found:

https://github.com/Trustroots/trustroots/blob/b1af480a9979a5597fbd7adc88a94dbb5ab4b840/modules/offers/client/views/offer-meet-edit.client.view.html#L62

Inside those brackets `{{ ... }}` Angular will print a date.
