### ISSUE TITLE
change hosting response after pressing red/green button

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#601]
"So, apparently, after pressing the green or red button, you can't change your mind, but after pressing "write back" you can."

**Comment by simison** [comment]
Pressing yes/no buttons sends a message (just like when you would type a message) and that's impossible to cancel.

Alternatives:

- status would be attached as a meta-data in messages (#233) but that's quite a bit more work
- store the message, keep the selection, and send the additional message when hitting "send" for the actual message

Idea of the feature was partially let users just send quick "no" replies without writing anything and add these buttons also to emails so that folks could just press "nope" and our reply-rates would go up.

I'll remove "good first issue" label because this has some complexity into it.
