### ISSUE TITLE
easy installation for devs

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#618]
It seems currently the only way to get this set up is if you have a _lot_ of knowledge of node, docker, and mongo.
It should be possible to set this up in less than 15 minutes with minimal knowledge of any of these, at least on Debian/Ubuntu and OSX.

How can we do this?

**Comment by guaka** [comment]
I'll simply start documenting my pain here:

## Debian/Ubuntu

`apt-get install nodejs` gives node 4.8.x, node needs to be installed in another way. How?

## OSX

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.8.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.1.0
3 info using node@v10.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle trustroots@0.3.3~prestart: trustroots@0.3.3
6 verbose lifecycle trustroots@0.3.3~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle trustroots@0.3.3~prestart: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/guaka/code/trustroots/node_modules/.bin:/Users/guaka/.composer/vendor/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/usr/local/git/bin:/Users/guaka/.composer/vendor/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin
8 verbose lifecycle trustroots@0.3.3~prestart: CWD: /Users/guaka/code/trustroots
9 silly lifecycle trustroots@0.3.3~prestart: Args: [ '-c',
9 silly lifecycle   'npm run install-if-no-modules && ./node_modules/.bin/check-node-version --package' ]
10 silly lifecycle trustroots@0.3.3~prestart: Returned: code: 0  signal: null
11 info lifecycle trustroots@0.3.3~start: trustroots@0.3.3
12 verbose lifecycle trustroots@0.3.3~start: unsafe-perm in lifecycle true
13 verbose lifecycle trustroots@0.3.3~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/guaka/code/trustroots/node_modules/.bin:/Users/guaka/.composer/vendor/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/usr/local/git/bin:/Users/guaka/.composer/vendor/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin
14 verbose lifecycle trustroots@0.3.3~start: CWD: /Users/guaka/code/trustroots
15 silly lifecycle trustroots@0.3.3~start: Args: [ '-c',
15 silly lifecycle   'concurrently --raw --kill-others --kill-others-on-fail \'gulp\' \'npm run start:worker\' \'maildev\' \'npm run agendash\'' ]
16 silly lifecycle trustroots@0.3.3~start: Returned: code: 1  signal: null
17 info lifecycle trustroots@0.3.3~start: Failed to exec start script
18 verbose stack Error: trustroots@0.3.3 start: `concurrently --raw --kill-others --kill-others-on-fail 'gulp' 'npm run start:worker' 'maildev' 'npm run agendash'`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
18 verbose stack     at EventEmitter.emit (events.js:182:13)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:182:13)
18 verbose stack     at maybeClose (internal/child_process.js:961:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
19 verbose pkgid trustroots@0.3.3
20 verbose cwd /Users/guaka/code/trustroots
21 verbose Darwin 17.6.0
22 verbose argv "/usr/local/Cellar/node/9.8.0/bin/node" "/usr/local/bin/npm" "start"
23 verbose node v10.2.1
24 verbose npm  v6.1.0
25 error code ELIFECYCLE
26 error errno 1
27 error trustroots@0.3.3 start: `concurrently --raw --kill-others --kill-others-on-fail 'gulp' 'npm run start:worker' 'maildev' 'npm run agendash'`
27 error Exit status 1
28 error Failed at the trustroots@0.3.3 start script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]
```

## Docker on Debian

How to install Docker? `apt-get install docker docker-compose`, yet:

```
ERROR: Couldn't connect to Docker daemon. You might need to install Docker:

https://docs.docker.com/engine/installation/
```

## Docker on OSX

Not sure how I got here:

```
trustroots    | npm info lifecycle trustroots@0.3.3~start:docker: Failed to exec start:docker script
trustroots    | npm ERR! Linux 4.9.87-linuxkit-aufs
trustroots    | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start:docker"
trustroots    | npm ERR! node v6.3.1
trustroots    | npm ERR! npm  v3.10.3
trustroots    | npm ERR! code ELIFECYCLE
trustroots    | npm ERR! trustroots@0.3.3 start:docker: `npm run prestart && concurrently --raw --kill-others --kill-others-on-
fail 'gulp --skipBower' 'npm run start:worker'`
trustroots    | npm ERR! Exit status 1
trustroots    | npm ERR!
trustroots    | npm ERR! Failed at the trustroots@0.3.3 start:docker script 'npm run prestart && concurrently --raw --kill-othe
rs --kill-others-on-fail 'gulp --skipBower' 'npm run start:worker''.
trustroots    | npm ERR! Make sure you have the latest version of node.js and npm installed.
trustroots    | npm ERR! If you do, this is most likely a problem with the trustroots package,
trustroots    | npm ERR! not with npm itself.
trustroots    | npm ERR! Tell the author that this fails on your system:
trustroots    | npm ERR!     npm run prestart && concurrently --raw --kill-others --kill-others-on-fail 'gulp --skipBower' 'npm run start:worker'
```

**Comment by simison** [comment]
There isn't really a ton we can do about pains of installing platform software like Node.js or MongoDB — apart from running them in a container like Docker or Vagrant, which then again is an additional layer for us to maintain.

Folks who work with these platforms and have the knowledge to contribute, usually have this stuff figured out already and Trustroots becomes "just another app" to run.

That said, while things need to be as easy as possible to run, there's also a balance between optimizing build and the stack. We can also just help each other out when anyone gets stuck, one by one. That's not too big of a task if someone is really willing to contribute to development. :-)


## Debian/Ubuntu

You seem to be missing steps mentioned in the manual:

https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Action items:**
- add a link to Linux install docs in the Readme.


## OSX

Looks like you're running on Node.js 10 and Trustroots is currently targetting version 8:
https://github.com/Trustroots/trustroots/blob/15a8bcebee8286eca1591f950a120420b2e08dd3/package.json#L11-L14

(I added Travis tests to track version 10 compatibility)

You can use `nvm` or `n` to run multiple versions of Node.js. If you use `nvm`, we have [.nvmrc](https://github.com/Trustroots/trustroots/blob/15a8bcebee8286eca1591f950a120420b2e08dd3/.nvmrc) that will switch your Node.js version to correct one when entering the folder.

I've been waiting for NPM to start supporting failing early on incompatible engine versions much like `yarn` does (it's a `npm` alternative). Meanwhile, we could warn about it manually using [`check-node-version`](https://www.npmjs.com/package/check-node-version).

**Action items:**
- Add `npx check-node-version --package` as a `prestart` script in `package.json`
- Add mention to readme that version 10 doesn't work currently.

Further reading: https://docs.npmjs.com/files/package.json#engines

## Docker on OSX

Not sure what's happening here but just saying that Docker stuff isn't super maintained and I'm not sure if there are strict enough version pinning there for images it uses (if not, things might've changed since it _was_ working).

Docker itself has a tendency to break stuff between updates so that doesn't help.

What was the command you ran and version of Docker you're at?

**Action items:**
- Ensure strict versions for Docker images
- Fix Docker setup if it's broken :-)

---

Additionally, we silently fail on incompatible MongoDB versions so that could be another manual check to do in the scripts if we wanted to make things smoother. In the past, I've trusted the clarity of docs for stuff like this but I've come to learn it's just not enough as required versions might change while you develop and developer shouldn't worry about them too much. :-)

**Comment by guaka** [comment]
> Folks who work with these platforms and have the knowledge to contribute, usually have this stuff figured out already and Trustroots becomes "just another app" to run.

Yes, but there's plenty of devs (and not-yet-devs) who don't work with these platforms.
I've used node in the past but now I've been trying for 2 months to get this set up.

from this page https://nodejs.org/en/download/, what to get for debian/ubuntu?

**Comment by simison** [comment]
I pressed _"Installing Node.js via package manager"_, it's a bit hidden there indeed!

**Comment by simison** [comment]
For Linux, we might just want to recommend using `nvm` since it simplifies things so much:

https://nodejs.org/en/download/package-manager/#nvm

**Comment by simison** [comment]
Hmm, so I actually just tested to run the app with Node.js 10 and no issues. Looks like I already solved Node.js 10 compatibility issues earlier this summer when they cropped up.

Let's debug your setup more in Saturday on a call.

**Comment by guaka** [comment]
------------------

## Install on Debian/Ubuntu

Install nodejs 8.x plus required dev toolset:

    curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    sudo apt-get install -y gcc g++ make
    sudo apt-get install -y nodejs

------------------

Then I run into this:

[10:28:30] 'styles' errored after 1.44 s
[10:28:30] Error: File not found with singular glob: /home/guaka/trustroots/public/lib/angular-trustpass/src/tr-trustpass.less (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/home/guaka/trustroots/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Glob.emit (events.js:211:7)
    at Glob._finish (/home/guaka/trustroots/node_modules/glob/glob.js:197:8)
    at done (/home/guaka/trustroots/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/home/guaka/trustroots/node_modules/glob/glob.js:688:12)
    at /home/guaka/trustroots/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/home/guaka/trustroots/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/home/guaka/trustroots/node_modules/glob/glob.js:764:12)
[10:28:30] 'build:dev' errored after 17 s
[10:28:30] 'develop' errored after 17 s
Recieved shutdown signal, shutting down now...
[Worker] Stopping Agenda...
[Worker] Agenda stopped.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trustroots@0.3.3 start: `concurrently --raw --kill-others --kill-others-on-fail 'gulp develop' 'npm run start:worker' 'maildev' 'npm run agendash'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the trustroots@0.3.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/guaka/.npm/_logs/2018-08-18T08_28_30_760Z-debug.log
guaka@tr:guaka@tr ~/trustroots ❯❯❯

**Comment by guaka** [comment]
Once it's installed and running it's also good to have some more info:

these things should probably mentioned be in README.md:
- [ ] (is there) test data? how to log in?
- [ ] how to deal with emails?
- [ ] words about `npm test`, any other test framework?
- [ ] GitHub - it's ok to create issues there when you encounter problems
- [ ] slack, other folks to contact with questions

**Comment by simison** [comment]
>how to deal with emails?

See the bit about Maildev in docs: https://github.com/Trustroots/trustroots/blob/5562b83dbab98a18bfb7e3a25d0145864aaf326f/INSTALL.md#4-start-the-app

Could be more visible though.

>words about npm test

https://github.com/Trustroots/trustroots/blob/5562b83dbab98a18bfb7e3a25d0145864aaf326f/INSTALL.md#running-tests

There definitely could be a doc explaining how to and when to write tests.

>any other test framework?

Wanna elaborate what do you mean?

>(is there) test data?

There's something but it isn't comprehensive enough and not tested in CI so it might break sometimes:

https://github.com/Trustroots/trustroots/blob/5562b83dbab98a18bfb7e3a25d0145864aaf326f/INSTALL.md#mock-data

An issue about extending mock data: https://github.com/Trustroots/trustroots/issues/462

>how to log in?

You need to create a user for yourself first via signup.

**Comment by simison** [comment]
Just pushed some changes: https://github.com/Trustroots/trustroots/blob/97346b853ae4dd93688b97560fbaa4ea88c61b68/INSTALL.md

**Comment by simison** [comment]
Docker setup should now work: https://github.com/Trustroots/trustroots/issues/662
