### ISSUE TITLE
Usage of proprietary Google service "Google Analytics"

### ISSUE THREAD

**Issue by Anth0rx** [Trustroots/trustroots#635]
I see that you are using Google Analytics as your web analytics service. Have you thought about switching to an alternative service? There is a free and open source project called [Matomo](https://matomo.org/). Relying on proprietary services for a free and open source project like Trustroots creates unnessecary dependencies. Switching to [Matomo](https://matomo.org/) would break those dependencies regarding web analytics and would give the control of the data back to the project and its community.

**Comment by simison** [comment]
Hey! Thanks for the feedback. Yep we know Matomo/Piwik very well, we've tried it here at Trustroots and at other big projects like Hitchwiki. It's not even nearly as effective as GA and it's real pain to host and we don't have time and energy to host software like that; we are too busy building Trustroots instead.

We have [a privacy page](https://www.trustroots.org/privacy) outlining all the similar services we use to build Trustroots, including instructions on how to opt-out from GA.

We rely a lot on external companies to run Trustroots; including hosting the servers, app and server monitoring, some analytics, sending out transactional emails etc. We host some of the analytics software ourself, but only where it makes sense. We very much trust e.g. our hosting company and email service provider — users obviously cannot opt-out from those since they're running at the backend. Google is different in that it runs in your browser and you can very well opt-out from it pretty easily.

Thanks for the heads up though, much appreciated!

**Comment by Anth0rx** [comment]
Thank you for your detailed answer. I understand what you mean :)

**Comment by guaka** [comment]
Topic on meta: https://meta.trustroots.org/t/replace-google-analytics-with-something-more-ethical/113/2
