### ISSUE TITLE
embeddable widget?

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#64]
@kamiel79 "something that people can put up on their blog"

e.g. like http://benn.org/
![screen shot 2014-12-19 at 10 14 21](https://cloud.githubusercontent.com/assets/54728/5502271/d84b8018-8767-11e4-8988-a59f2d4594aa.png)

**Comment by simison** [comment]
https://github.com/joeframbach/jquery-couchsurfing-widget

**Comment by joeframbach** [comment]
I don't think that couchsurfing widget works as-is. Couchsurfing updated their code a while ago, and I haven't updated the widget.

**Comment by joeframbach** [comment]
I once applied for a job with CS with that widget as part of a cover letter. They weren't interested in even talking to me. I wouldn't count on any engagement with them.

**Comment by simison** [comment]
No worries @joeframbach. :-)

Have you seen [Trustroots.org](https://www.trustroots.org/)? — so we're building something like CS here from a bit different perspective. Check also [Hackercouch.com](https://hackercouch.com/).

Anyway, @kamiel79 asked quite a few times from me if he could build something like that widget of yours, so I thought I'd just put it down here since I stumbled upon it.

I'm planning to test your Agenda dashboard since we use Agenda here. It looks pretty impressive! Good job. :-)

**Comment by simison** [comment]
Closing this as I'm cleaning issue list and this won't be on todo very soon...
