### ISSUE TITLE
Additional newline when inserting newline in a message

### ISSUE THREAD

**Issue by Anth0rx** [Trustroots/trustroots#641]
When writing messages to others and inserting a newline it is displayed as two newlines in the message history.

**Comment by sharunspi** [comment]
show details regarding common places .

**Comment by AbhyudayaSharma** [comment]
Hi! I'd like to work on this. Could I please get a code pointer?

**Comment by jakubkarabula** [comment]
Hi @Anth0rx @simison 

I have investigated this issue. It's not showing "two newlines" but rather creates a new `<p>` element with every `enter` and `<br>` with every `shift + enter`.
There was a discussion on medium-editor issues page to allow to add simple `<br>` when using `enter`, you can see it here https://github.com/yabwe/medium-editor/issues/70
But they decided it's the expected behaviour and I don't see any easy way around it.

This second `<p>` element is shown lower because `<p>` in your project have assigned global css `margin: 0 0 10px;`

So to fix the unnecessary margin for the messages you or I can add something like `.panel-body  p { margin: initial; }` to css/less.
What do you think?

**Comment by guaka** [comment]
@Anth0rx can you check if this fixes it for you?
