### ISSUE TITLE
Automatic authentication via links in emails

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#647]
we can send a "login link" with each email

like slack or okcupid

<img width="521" alt="image" src="https://user-images.githubusercontent.com/54728/44580191-53a5a680-a799-11e8-82bf-75295d320546.png">

with one-time token that's valid for a limited time?

**Comment by simison** [comment]
>with one-time token that's valid for a limited time?

Yep, there are loads of libraries to handle this so it's mostly plug-and-play and being careful not to expose security issues. Tokens need to persist in MongoDB.

It's pretty safe to have those links in the email because if someone has access to your email, they also have access to TR account via password reset.

The only problem are emails that someone forwards to someone, but one-time tokens, not making _every_ link tokenized in the email and limiting validity in time should protect enough.
