### ISSUE TITLE
node not binding to external network interface?

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#648]
local.js:
- set external.host.name
- port 80

`sudo npm start`

now:
- `w3m external.host.name` works on server
- but from laptop no connection to `external.host.name:80`
- with apache installed `external.host.name:80` works fine

**Comment by guaka** [comment]
Maybe node is bound to `lo` and not to `eth0`?

**Comment by simison** [comment]
I'm not quite sure what action there would be needed or what was the goal?

>with apache installed external.host.name:80 works fine

Sounds about right, that's how the production server also runs (just using Nginx instead of Apache). In production the app runs on localhost and we proxy to it.

Feel free to re-open but please do elaborate more on what was the goal. 😁

**Comment by guaka** [comment]
The goal was to set up a simple dev server that doesn't go through nginx or
apache.

I'll create a new issue.

**Comment by simison** [comment]
Now that also the Docker setup works and local dev setup is more robust, are there actual needs to run an external dev server outside localhost?

**Comment by simison** [comment]
>Yes, we need a testing server.

Totally :thumbsup:

>But that can be with a setup very similar to production

Exactly. :-)
