### ISSUE TITLE
best way to change static texts on production?

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#660]
I want to add some more text to https://www.trustroots.org/volunteering and other static texts.

What's the best/fastest way to do this?

**Comment by simison** [comment]
You can modify contents on those pages under `pages` module: https://github.com/Trustroots/trustroots/tree/11dd9b27934eb0a7d66f38c786afdbdb21912749/modules/pages/client/views

Since it's actual app code (instead of just readmes/docs), please do changes via PRs so that CI runs tests and linters on them. Feel free to merge without review, though also nice if I can review first. :-)

Make also sure to test changes locally (in desktop sized browser and narrowed down mobile view) to make sure it looks good.

**Comment by guaka** [comment]
been doing it
