### ISSUE TITLE
twitter auth broken: WSOD

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#689]
https://www.trustroots.org/api/auth/twitter gives WSOD

<img width="807" alt="image" src="https://user-images.githubusercontent.com/54728/46157302-ae8c5b00-c27b-11e8-8c51-a50f0cbbda73.png">

**Comment by topalavlad** [comment]
I created a Twitter app for the `clientID`, `clientSecret`, but I'm not sure what the `callbackURL` for Twitter should be. Anyone? ^_^

**Comment by topalavlad** [comment]
I set this up on my local environment and it seems to be working locally with the latest code. On www.trustroots.com, it seems that `user = {{ user | dump | safe }};` in `layout.server.view.html` gets an empty value for user but unfortunately I'm not sure how I can debug this further. 

Any suggestions? Thanks.

![locally](https://user-images.githubusercontent.com/2983957/48301913-ae7bae00-e4fd-11e8-94a8-e8a2653b543e.png)

**Comment by simison** [comment]
This should be fairly simple to fix though, probably just depends on how
urls are configured at Twitter end.  I don't think anything specifically
has changed with their oauth.

If it's more work, then agreed.

On 25 Nov 2018 00:29, "Guaka" <notifications@github.com> wrote:

https://www.trustroots.org/statistics twitter 1.8%

Maybe it's better to ditch the twitter oauth? @simison
<https://github.com/simison>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Trustroots/trustroots/issues/689#issuecomment-441399982>,
or mute the thread

**Comment by guaka** [comment]
Do you think it is ok to ditch twitter auth if this is not fixed by 2019-01-24? :)

**Comment by simison** [comment]
Had to re-apply Twitter API access.

**Comment by simison** [comment]
Also adjusted oauth callback URL setting.

Works now 👍 

Thanks both for looking into it!
