### ISSUE TITLE
profile link to hitchwiki profile or user contributions?

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#713]
It's really nice (and somewhat relevant) to see stuff like http://hitchwiki.org/en/Special:Contributions/Eazy :)

@simison do you think this is a good idea?

**Comment by simison** [comment]
Since Hitchwiki isn’t really “social network” where folks you check for shared connections and shared interests, having a link there doesn’t seem like adding a lot of value? How would it be useful for members to see that someone has Hitchwiki account?

More over I’d prefer to stay away from freeform username fields as much as possible and prefer only services with oAuth connections; it’s more “trusted” connection. Hospitality networks are impossible to ignore and none support oAuth so we have them as free text right now.

Note that folks who are really passionate hitchwiki contributors can still add links to their description field.

**Comment by guaka** [comment]
OK, makes sense :)
