### ISSUE TITLE
Showing results as a list in the search results tab

### ISSUE THREAD

**Issue by Regenwasser** [Trustroots/trustroots#721]
_I heard that when designing Trustroots there was the plan to also show all search "results" as a list, but there's no issue for it yet - until now._ 

The decision probably came from user stories such as "As a user I want to be able to quickly scan search results, so I spent less time finding the person I want to contact." and is still valid today.

### **Current implementation:** 

The space for the list is not populated yet and shows only one result if clicked on a marker.

![image](https://user-images.githubusercontent.com/1645834/47071112-f9522080-d1f2-11e8-930c-96a9c458b4eb.png)

### **To do:** 

List shown on both mobile and desktop.

_________________________________________
There's also includes #610 - **Search as list instead of map**, but that is about optional ways of searching to perserve data and is more mobile related. Here (I assume) the plan was to also enable the possibility of filtering or expanding search results by moving the map as a next step.

So at least on desktop this issue does not describe searching "instead of map", but "with the map".

**Comment by simison** [comment]
Thanks! 👍 

> There's also includes #610 - Search as list instead of map, but that is about optional ways of searching to perserve data and is more mobile related. Here (I assume) the plan was to also enable the possibility of filtering or expanding search results by moving the map as a next step.
>
>So at least on desktop this issue does not describe searching "instead of map", but "with the map".

I feel it's the same feature (same goals) but how it behaves might be little different in small screens vs desktop. I closed the other issue since this is more elaborate.

**Comment by Regenwasser** [comment]
Very closely related, yes. The way I see it is that this issue here can include #610. 

I didn't comment under #610 as it seems to describe the mobile view only and to be motivated mainly by that one use case (bandwidth and data).

**Comment by danidanitr** [comment]
Hi, we are working on it. We did a grid. Thought for desktop there is space and easy for the eye to view a grid. In mobile with scrolling. So far, this:

Wider width for results
The info of each user is better now: you don't need to click on each to see their rate reply, within hours and waste time opening and closing windows.
Changed HOSTING as title of "accommodation" for actually "accommodation" and the hosting status goes in the middle of the 6 first items creating a nice contrast.

Rest stays the same.

Do you like it?
![results1](https://user-images.githubusercontent.com/43136016/47081769-d97b2680-d20b-11e8-90a9-8d611781f42e.jpg)

Mobile version very soon.

**Comment by danidanitr** [comment]
Ah, and same green of trustroots lowered to 6% transparency, creating a nice contrast and we don't need then lines or spaces to create a grid.

**Comment by simison** [comment]
Nice!

A few pointers:
- Let's ensure we don't use font sizes smaller than 14px for readability reasons.
- Could you mock how it looks like when there are e.g. 15 common tribes or accommodation description is missing? I.e. mixed content like often is the reality.
- Probably best if one card per row (and not two), makes it more readable? More scrolling isn't that bad since people cannot concentrate on more than one card at a time anyway.

**Comment by danidanitr** [comment]
Ok Mikael.

**Comment by Regenwasser** [comment]
@danidanitr Yes, this is great to hear, especially that you also right away change some information. Actually, it covers some things that I already was told to put into a Google doc, but that I never followed up on (should have created more issues). You can find it [here](https://docs.google.com/document/d/1G8ug00hQgNc-ipnikdTuI3BkLG2vZpu9lVH6kgoa3ss/edit). 

In it I briefly try to explain why I believe hosting description and mission isn't good here. 

Dropping the gender is also be an option once the search let's people filter by gender, because then the information would either be the same everywhere or just not be important to the user.  

There are also other things to think about, like age? Do Trustroots users heavily filter by age and isn't the picture showing enough? Think about the information that is absolutely necessary for a user to decide to open someones profile if you looking for someone as a host _or_ to meet.

I think personality is the most important part (competitors seem to think the same). 

Also share the same concerns about the grid for all the same reasons that @simison mentioned.

**Comment by danidanitr** [comment]
@Regenwasser we also implemented the aspects you mentioned previously:
- Giving more importance to the community and not only to the hosting = By highlighting with same trustroots green the tribes the user is in position next to the first user's info.
- We took the gender away but kept the age - **We think age is still important, you?**
- We add about me content instead of the motto - **What you think? We think this shows more about the person and the probability they have about me in blank is lower than with the motto so most of the times there would be info displayed**

> The red point color idea, we thought of creating a new dot with the rainbow color. This dot would represent everyone who wants to be on the map (and in the tribes) but can't host. (we will discuss this in another issue)

@simison, following your points:

- Let's ensure we don't use font sizes smaller than 14px for readability reasons.
- Probably best if one card per row (and not two), makes it more readable? More scrolling isn't that bad since people cannot concentrate on more than one card at a time anyway.
![results_2](https://user-images.githubusercontent.com/43136016/47096834-58825600-d230-11e8-8f0d-9cb8a68e4151.jpg)

- Could you mock how it looks like when there are e.g. 15 common tribes or accommodation description is missing? I.e. mixed content like often is the reality. - **Second pic shows less space when accommodation is blank, which one you like more? When space is blank so the user notices easily there is no info or when the design readjusts?**
![results_2-incase](https://user-images.githubusercontent.com/43136016/47096906-7a7bd880-d230-11e8-85a5-f2d09c0512c0.jpg)
![results_2-incase2](https://user-images.githubusercontent.com/43136016/47096929-8798c780-d230-11e8-8ee8-9d2e58386895.jpg)

- Ensure contrast between background and text meets WCAG contrast standards: https://contrastchecker.com/ -- **We used same colors, therefore same result of compatibility.**
![dadadad](https://user-images.githubusercontent.com/43136016/47096993-b1ea8500-d230-11e8-9e86-47cbed256006.jpg)

How hovered state should look like:
Pressing dot on the map, what happens?
**When pressing on the dot on the map, the left panel updates with a fading effect**
![results_2_oneclick](https://user-images.githubusercontent.com/43136016/47098139-0131b500-d233-11e8-82f9-3858845177d7.gif)

Hovering card from the list, how does it look like?
**Turns into grey with fast fading**
![results_2_hovering_on_user](https://user-images.githubusercontent.com/43136016/47098968-9b462d00-d234-11e8-9f0c-dbfbbb22e98b.gif)

**Comment by danidanitr** [comment]
We wait for your feedbacks :+1:

**Comment by danidanitr** [comment]
I like how we've come up with the idea of simplying the words of accommodation, hosting and the colors by putting the colors and the word HOSTING together. So the color will indicate the state of the hosting (following the logic of the map) and we get rid of YES, MAYBE OR NO, at least for what's displayed on the card. Then in each profile's settings ppl can still see in the UI = yes, maybe or no when setting up their accommodation.

**First changes, @simison** 
- linking to tribes isn’t so important in this view so better keep them text color for less distraction
- Text still feels little small? Gray text is probably same as current versions at the site (12px) but the amount at the live site is way less. is the main text 14px? YES, just photoshop did it too hard so used LIGHT version of Segoe UI
- “hosting” in the list feels repetitive due “accommodation” section (and two different words, let’s try to use one word across the site) = New idea = Color and hosting in one
- Justified text spacing usually doesn’t work great in web for readability, partly due lack of automatic hyphens. (edited)

to do in the next one after ur feedback:
- I’m worried about limiting space to three columns and not having flexibility for long names and usernames.
- Probably okay to show “…” or “and 10 more” if there are a lot of common tribes instead of showing the full list.
- I’ve learned that allcaps titles aren’t that easy to read. not a blocker but something to consider/play with.

![results_3](https://user-images.githubusercontent.com/43136016/47168954-8f28a100-d302-11e8-97dc-7041cd9b3dba.jpg)

**Comment by danidanitr** [comment]
I like how we've come up with the idea of simplying the words of accommodation, hosting and the colors by putting the colors and the word HOSTING together. **What do you think?** So the color will indicate the state of the hosting (following the logic of the map) and we get rid of YES, MAYBE OR NO, at least for what's displayed on the card. Then in each profile's settings ppl can still see in the UI = yes, maybe or no when setting up their accommodation.

First changes, @simison

- linking to tribes isn’t so important in this view so better keep them text color for less distraction
- Text still feels little small? Gray text is probably same as current versions at the site (12px) but the amount at the live site is way less. is the main text 14px? YES, just photoshop did it too hard so used LIGHT version of Segoe UI
- “hosting” in the list feels repetitive due “accommodation” section (and two different words, let’s try to use one word across the site) = New idea = Color and hosting in one
- Justified text spacing usually doesn’t work great in web for readability, partly due lack of automatic hyphens. (edited)


to do in the next one after ur feedback:
- I’m worried about limiting space to three columns and not having flexibility for long names and usernames.
- Probably okay to show “…” or “and 10 more” if there are a lot of common tribes instead of showing the full list.
- I’ve learned that allcaps titles aren’t that easy to read. not a blocker but something to consider/play with.

Rick will accompany with the search of the perfect results design.


![results_3](https://user-images.githubusercontent.com/43136016/47169724-8933bf80-d304-11e8-93a0-5cd8bf2fca2d.jpg)

**Comment by danidanitr** [comment]
I like how we've come up with the idea of simplying the words of accommodation, hosting and the colors by putting the colors and the word HOSTING together. What do you think? So the color will indicate the state of the hosting (following the logic of the map) and we get rid of YES, MAYBE OR NO, at least for what's displayed on the card. Then in each profile's settings ppl can still see in the UI = yes, maybe or no when setting up their accommodation.

First changes, @simison

- linking to tribes isn’t so important in this view so better keep them text color for less distraction
- Text still feels little small? Gray text is probably same as current versions at the site (12px) but the amount at the live site is way less. is the main text 14px? YES, just photoshop did it too hard so used LIGHT version of Segoe UI
- “hosting” in the list feels repetitive due “accommodation” section (and two different words, let’s try to use one word across the site) = New idea = Color and hosting in one
- Justified text spacing usually doesn’t work great in web for readability, partly due lack of automatic hyphens. (edited)

to do in the next one after ur feedback:
- I’m worried about limiting space to three columns and not having flexibility for long names and usernames.
- Probably okay to show “…” or “and 10 more” if there are a lot of common tribes instead of showing the full list.
- I’ve learned that allcaps titles aren’t that easy to read. not a blocker but something to consider/play with.

Morty will be our guide in the search of the perfect results design, let's welcome him :+1: + a lovely attribution: By Danielobich 23 [<a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0 </a>], <a href="https://commons.wikimedia.org/wiki/File:Imagen_de_la_serie_Rick_y_Morty.webp">from Wikimedia Commons</a> 😂

![results_3](https://user-images.githubusercontent.com/43136016/47169962-2e4e9800-d305-11e8-925a-0c071371eddd.jpg)

**Comment by Regenwasser** [comment]
> Morty will be our guide in the search of the perfect results design, let's welcome him 👍

Haha, I don't like that show, but I do love that addition. 

Here's your delayed (& now extra long) feedback:

> The info of each user is better now: you don't need to click on each to see their rate reply, within hours

One of these would be enough maybe, since they show very similar info. 

The reply percentage would work best for me. Since the hour calculation is just an average. It is faster sometimes and I don't on how many messages that's based on.

> We took the gender away but kept the age - We think age is still important, you?

Personally for me it is kinda important, but I think I probably make the decision often unconsciously via the picture (before seeing the full profile). However, generally, I think that it's probably not very important to these alternative, open, travelers here on Trustroots that stay with strangers.

I showed you for example the BeWelcome and Couchsurfing screenshots and they lack the age, so they seem to think the same and maybe made some research or collected enough feedback over the years. But that could be a coincidence and if you look at other hospitality networks too it shows a different picture?

> We add about me content instead of the motto - What you think?  
 
Yes, good decision. 

> New idea = Color and hosting in one

Two things here: 
1. The "hosting" in orange and green is misleading. People don't know that it's "maybe". That's adding cognitive load and the "maybe" turns up on the profile, so it should use the same description here.

2. I also would like to move away from adding negative colours like orange from "maybe". I'd propose a Hosting (in Green font). And "Maybe hosting" (in black). Hosting at most in bold, but not so strongly with a whole colourful box around it. 

> Changed HOSTING as title of "accommodation" for actually "accommodation" 

I said earlier that I think it should be removed. Here is again "why" from the Google doc: 

_"For someone who just wants to meet someone this information is not useful."_

That means some use cases scroll over a lot of useless info. 

And further and more important:

_"Most users that are looking for the host care first about the person that I’ll be staying with and less about the actual hosting situation."_ [Kasper +1'd that part.]

Here's what I thought: We are not airbnb. Our business isn't selling rooms. On airbnb the hosting details are the most important: How big is the flat? Private room? Features?

On Trustroots users care most about the people, because they're happy with some couch anyway. They  read the about me and then check out the profile. If they like the profile (and maybe also read the references), they check out the hosting situation and make it work. 

We don't want to make it so easy that someone picks out host based on the hosting info, like picking a airbnb. And also, we want to list many profiles so we can easily scroll over them on all devices. Do you agree?

**Comment by simison** [comment]
>Then, for that we will need some kind of instruction to tell user what photos to upload. Not that be give importance to the size of the pic and then we get photos of whales XD

I'm not sure if I follow, could you elaborate on what you meant?

**Comment by simison** [comment]
What do you think if we change "Hosting [YES]" into something like this:

<img width="242" alt="image" src="https://user-images.githubusercontent.com/87168/47267112-d5227680-d547-11e8-9291-da90cfd068ae.png">

It's a bit more inclusive for those who have problems reading a bad-contrast text (yellow-white especially being a bad offender https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=F0AD4E)

**Comment by Regenwasser** [comment]
Good, point. I also already suggested stripping the colours and changing it to "Hosting" and "Maybe hosting" in my last comment, so I agree here.

We could have the font of "hosting" or your text green (it's a positive collour! The user is hosting - and also it highlights the profile, so it receives more clicks) and keep the "Maybe hosting / I might be able to host" in black. Neutral.

@danidanitr: No, I didn't mean two columns. Just that removing the hosting info (and other stuff) will enable us to list more profiles under each other.

Yes, I think the "mission" is really necessary either, so if it's helpful space wise you can take it off.

**Comment by danidanitr** [comment]
About instructions for the photo = deleting other info means the photo is more relevant, therefore the photo must show who the person really is. If then this user upload a bluesky, animals, a big field, or whatever other impressive travelling photo, the photo becomes useless.

About hosting/not hosting/orange/green/colours = I put it this way, all green. I think a dot is too little. **What you think Mikael?**

About tribes, I put it below the username basic info so they provide a better feeling of how this person contributes to trustroots. _And not on the bottom as an extra info as now._

About me = personally I would even delete this one. But I ask you guys first. We thought about it with Kasper.

Anyways, when the users click to expand the profile then they would see the About me, or any other field we require in the future to be filled up with info. I think it is a good idea not to show about me. Hitchikers, cyclist, whoever travelling, do they really care about an "about me" ? I think all comes down to "let's see on the pic, oh cool, I feel a good vibe, I need help/wanna share a good time, contact him/her" - open profile = I read more info (oh actually he/she is also this or that) = oh I'm even more interested in writing to her/ o actually is different than what I thought and I don't write. Done.

![results_4_2](https://user-images.githubusercontent.com/43136016/47272303-1b95c680-d584-11e8-9a78-86eedb072111.jpg)

**Comment by danidanitr** [comment]
Morning :+1: 

About adding contacts, to me it looks when all info about hosting in one line like displayed now. **Ok?**
About "I can host", I suggest to give it a bit more weight. **Ok?**
About "deleting ABOUT ME" it may look now very much like the ones on CS but also other sites, not hospitality-community related actually use the same structure, basically deleting redundancy. **So OK.**
Tribes "grey", decided to put them in the same colour as the initial info of the person. **What are your thoughts about this?**

![results_5](https://user-images.githubusercontent.com/43136016/47280967-19aa2280-d5d9-11e8-8b13-ee6b5fba58f5.jpg)

**What about putting the "I may be able to host" in italic?** It would emphasise it a little bit more avoiding to get mixed with the word "references" and "contacts". I think this could be a good alternative to the orange maybe, just so at least there is some some way to let the eye detect it easily.
![cursivemaybe](https://user-images.githubusercontent.com/43136016/47281011-3cd4d200-d5d9-11e8-9548-c7dab4cbf9e4.png)

The upper - right part I'm thinking it could be use for future badges, a special status for that user, let's say if we classify the members onboard volunteering with an icon for example, or the classic ambassador figure, or when someone will be giving speeches and organising evens in the future. I made a quick mockup to illustrate that idea. **Thoughts?**
![results_5_badges](https://user-images.githubusercontent.com/43136016/47281138-da300600-d5d9-11e8-8635-70376e14d4f1.jpg)

**Comment by danidanitr** [comment]
I hope this time github works. It kept updating and then deleting my messages. So:

About me title = deleted = info extended
I can host = more weight
About contacts = not sure it is necessary, but ok it fills up the space
Numbers of contacts = semibold
Tribes = back to grey color to go together with the initial profile info
![results_5](https://user-images.githubusercontent.com/43136016/47283440-b5d92700-d5e3-11e8-86c0-9574b6822baf.jpg)

**Idea**
I may be able to host = italics = this way we avoid it mixes with the words references and contacts. Creates a subtle difference when scrolling.
![results_5_cursive_maybe](https://user-images.githubusercontent.com/43136016/47283435-b376cd00-d5e3-11e8-9a68-2f220e123b7a.png)

**Idea**
Upper-right part = used for badges = icons we invent in the future to represent who's completed a hitchhiking competition, who's part of the volunteer team, so on. It can be very nice.

**Idea 2**
This icon thing brought me to think we could do the same with the icons we're designing for the tribes. But then I thought some of them are difficult to understand at a small size and so I went back to the idea of tribes displayed through words.

**Comment by danidanitr** [comment]
I hope this time github works. It kept updating and then deleting my messages. So:

About me title = deleted = info extended
I can host = more weight
About contacts = not sure it is necessary, but ok it fills up the space
Numbers of contacts = semibold
Tribes = back to grey color to go together with the initial profile info
![results_5](https://user-images.githubusercontent.com/43136016/47283440-b5d92700-d5e3-11e8-86c0-9574b6822baf.jpg)

**Idea**
I may be able to host = italics = this way we avoid it mixes with the words references and contacts. Creates a subtle difference when scrolling.
![results_5_cursive_maybe](https://user-images.githubusercontent.com/43136016/47283435-b376cd00-d5e3-11e8-9a68-2f220e123b7a.png)

**Idea**
Upper-right part = used for badges = icons we invent in the future to represent who's completed a hitchhiking competition, who's part of the volunteer team, so on. It can be very nice.

**Idea 2**
This icon thing brought me to think we could do the same with the icons we're designing for the tribes. But then I thought some of them are difficult to understand at a small size and so I went back to the idea of tribes displayed through words.

**Comment by vtrrsl** [comment]
Hi! Is there any work in progress on this one? I was thinking about giving it a go otherwise!

**Comment by Akronix** [comment]
AKAIK there isn't, so please go ahead!

**Comment by Akronix** [comment]
@vtrrsl are you in the slack chat? You can ask any questions you face there!

**Comment by simison** [comment]
This is probably quite complex so you might want to start with something more simple. ;-) additionally, we'll want to refactor the search view into react first before adding code on top of the old angular version.

if you do want to go ahead with this, let's talk on Slack first about steps to proceed/split this work into chunks that are easier to manage. :-)

**Comment by vtrrsl** [comment]
I understand! Wasn't aware of it needing to be refactored from Angular, then it feels a bit bigger ;) Still interested since it's the number one thing I would like to have in the app :) But it's probably a good idea to start with something else to get used to the react part of the code base and not jump into a whole refactor. Do you have any issues you can point to?

Cheers!

**Comment by Akronix** [comment]
Maybe one of the components still missing in https://github.com/Trustroots/trustroots/issues/1019 @mrkvon ?

**Comment by mrkvon** [comment]
@Akronix @vtrrsl #1334 which i just opened could help

I think in #1019, only tribes panel is not migrated (it's a part of modules/users/client/views/profile/profile-view-about.client.view.js), so it's for grabs. Or see the issue #1334 to pick something you may like to work on. :slightly_smiling_face:

And please edit that issue to your heart's content. :heart:

**Comment by vtrrsl** [comment]
Thanks! I'll take a look 👍
