### ISSUE TITLE
Improve mobile footer navigation

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#741]
These icons at "editing profile" footer navigation are terrible because it's unclear what they stand for:

<img src="https://user-images.githubusercontent.com/87168/47254084-90261380-d465-11e8-8617-7ec9b12d4123.png" width="320">

They're icons because text labels didn't fit horizontally even on bigger mobile screens. We can significantly make this easier with some small improvements.

The navigation _should_ be text-based, not icon based, like rest of the navigations, e.g. viewing profile looks like this:

<img src="https://user-images.githubusercontent.com/87168/47254383-615e6c00-d46a-11e8-874f-c6be29130a45.png" width="320">

The thing is that not everything will fit on that navigation, especially on very small screens such as iPhone 5S with 320px wide, see how e.g. profile page behaves:

<img src="https://user-images.githubusercontent.com/87168/47254099-e85d1580-d465-11e8-94fa-89d69b733ffe.png" width="420">

Thus we need a navigation that you can scroll horizontally on touch screen and more navigation items would appear:

<img src="https://user-images.githubusercontent.com/87168/47254150-a08abe00-d466-11e8-9134-a940f812e63e.png" width="320">

Hope is that this could be mostly implemented using just CSS, but little JS might be needed to show/hide the arrow.

**Comment by Regenwasser** [comment]
Instead of doing this have you considered just removing some of these tabs? 

There's two tabs that we can look at: Contacts and About/Overview. 

I'd argue that **[Contacts]** normally is the most unnecessary one in this navigation, because it's not part of the regular hosting/meeting/surfing flow, so why should one be able to quickly access this at all times? 

Without looking at analytics we can guess that this is the least visited tab. People that check out a profile look at **[Overview][About][Hosting]** and not the contacts. Common contacts with the user are displayed on their profile anyway. We could just list "Contacts: Number" under [About] and a link to the contacts there. However, that's a little bit of extra work...

But also overview & overview don't have to be separate (actually, there's even a bug that pre-selects both tabs currently). The words "about" and "overview" are used for the same thing on many other communities. So, we can just merge the two as it is on Desktop? [quick fix?]

A big part of this issue is that once we have references that would mean that that we have to add another tab for references with the number of references shown (according to your mockup in #718), so **we need that space**.

**Comment by simison** [comment]
Valid points! No, I didn't consider removing tabs.

>I'd argue that [Contacts] normally is the most unnecessary one in this navigation, because it's not part of the regular hosting/meeting/surfing flow, so why should one be able to quickly access this at all times?

This is pretty quick fix that we could indeed do. Common contacts list can also be pretty long so would be great to have toggle to make it shorter as well.

>But also overview & overview don't have to be separate ... The words "about" and "overview" are used for the same thing on many other communities. So, we can just merge the two as it is on Desktop? [quick fix?]

Yap this is a quick change; the concern was not to have super long pages to scroll on mobile (=not a great experience), but we should implement [hiding long contents](https://github.com/Trustroots/trustroots/issues/728#issuecomment-431593994) first and when that's done, combine overview+about+contacts pages on mobile.

**Comment by simison** [comment]
Noting that most pressing issues with the footer navigation are for _editing_ profile -view (those icons) where combining different views is quite a bit harder.

**Comment by thomasstep** [comment]
I am interested in looking into this. What are the requested words to replace each icon in the edit profile view?

**Comment by simison** [comment]
Hey! Excellent :-)

Labels should be:

- Profile
- Locations
- Photo
- Networks
- Account
