### ISSUE TITLE
301 redirects

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#742]
We need a good way to handle 301 redirects in the codebase.

- [x] https://www.trustroots.org/tribes/lgbt is now 301 in nginx, should be 301 in codebase to https://www.trustroots.org/tribes/lgbtq
- [ ] https://www.trustroots.org/support should 301 to https://www.trustroots.org/contact (they're the same content now)  @laazee 
- [x] https://www.trustroots.org/invite should redirect to https://www.trustroots.org/signup
- [x] https://www.trustroots.org/tribes/vegans-vegetarians to /tribes/veg (after changing slug in database)

**Comment by simison** [comment]
I did the redirect temporarily at Nginx config for now, but this should happen at the backend. I'll keep this open until then.

Tribe DB model has `slugHistory` exactly for this purpose.

**Comment by guaka** [comment]
also good to redirect https://www.trustroots.org/invite to signup

**Comment by guaka** [comment]
Should we use `/support` or `/contact`? What was the rationale for adding one?

**Comment by simison** [comment]
>Should we use `/support` or `/contact`? What was the rationale for adding one?

I don't remember now, but looks like they serve otherwise identical pages except support route supports extra `?report` thing and they have different titles:

https://github.com/Trustroots/trustroots/blob/7197c173a0ea062f12f7332cfd8c3f031a4c6e51/modules/support/client/config/support.client.routes.js#L11-L32

If you want to modify contact to redirect support also in Angular-router, here's how:

https://github.com/Trustroots/trustroots/blob/a743828a815f3b69eedc194606e2379faf89b5e8/modules/users/client/config/users.client.routes.js#L12-L25

...or it could just be removed from Angular router completely. Would require checking there are no `ui-router="contact"` anywhere around and replace those with `support`-links.
