### ISSUE TITLE
Do not show common tribes twice in the profile overview

### ISSUE THREAD

**Issue by Regenwasser** [Trustroots/trustroots#744]
This quick fix _(looks like it was probably planned initially)_ could be a small relief to the discussion that lead to #728.

### Current Implementation:

![image](https://user-images.githubusercontent.com/1645834/47257850-510eb700-d493-11e8-98e7-854d8f0c0bca.png)

### Expectation:

![image](https://user-images.githubusercontent.com/1645834/47257880-ed38be00-d493-11e8-8eeb-b5679d939b8e.png)

(Whoever does that can make the common tribe links, look like other links too.)

**Comment by simison** [comment]
Perhaps we could:
- get rid of the list on top:
    <img width="218" alt="image" src="https://user-images.githubusercontent.com/87168/47265563-6dadfc00-d532-11e8-8a7e-ccc9669413ad.png">
- Show common tribes always on top of the list
- Highlight them visually more so that it's clear which tribes users share in common

Thoughts?

**Comment by Regenwasser** [comment]
Yes, there are two empty spaces separating the tribes, so I surely don't like the thing you took a screenshot off either.

Your suggestion is also good. I chose the other way, because in the mentioned issue people talked about wanting to collapse the list of tribes, because it takes a lot of space. And this here has also some redundant information, like the number of members of the tribe that I'm already a member off. Maybe we could take all the numbers out? 

Either way: I'm happy with "**Do not show common tribes twice on profile overview**" as the only acceptance criteria.

**Comment by petr-hajek** [comment]
Good idea. I'd be more in favour of not displaying the full badge for common tribes, because it contains info user doesn't need (join button, followers). It could also contain some header like Other Tribes.

Thinking about it in incremental terms, I'd say it's better to keep the common tribes intact in this issue and possibly create new issue for the common tribes redesign afterwards. Only reason would be if you think that user might be more prone to skip the common tribes part because they are just text compared to the badges for other tribes.
