### ISSUE TITLE
use beta-tester role for "independent" features

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#766]
**Is your feature request related to a problem? Please describe.**

Currently we release stuff directly to everyone on the network. This also requires a high level of perfection before we can release something, which comes with high discussion to code ratio.

It will be beneficial if we can release (some) features to a small subset of users, with the `beta-tester` role. E.g. for references, or tribe discussions, we add a big fat warning that "all this data may disappear" and we can move much faster, have discussions about functional stuff.

**Describe the solution you'd like**
I want:
- [ ] users can be assigned the `beta-tester` role
- [ ] some functionality will be released only to  users with the `beta-tester` role. E.g. references #718 are already a bit trickier than something completely independent, but still possible, by only allowing references between 2 users that both have the `beta-tester` role.

**Describe alternatives you've considered**
These alternatives can be done regardless of using the `beta-tester` role.
- Consistently using the feature request template from now on: https://github.com/Trustroots/trustroots/issues/new?template=feature_request.md
- Create a process for new features: how do we do this?

**Additional context**
- Beta testing like this worked really well for couchsurfing in 2006.

**Comment by simison** [comment]
Nice idea and definetely worth exploring.

I see a few complications that need to be thought carefully:

- It's a bit harder to think how to go about "two-sided" features like "references", as you mention. Probably just let folks leave references to other beta-users, but it indeed needs a bit more care how to expose features. We can work our way around this.
- Background job worker script doesn't have context of a user, so we would need to make sure not to put anything that relies on background jobs behind a feature flag, so that users would get their notifications etc. It might be difficult to reson about those boundaries:
   - Does the job require DB schema loaded?
   - Can a job that sends nudges to everyone be enabled?
   - Can a job that nudges users who've used the feature be enabled?)


We're about to implement "feature flags" config object for References anyway, which is useful for something like this as well.

Basically we'd have in our config:

```
{
    featureFlags: {
        featureName: false
    },
    betaFeatures: [ 'featureName' ]
}
```

- Allowing keeping feature always on for development environments and off for production.
- Allowing turning feature on in production for beta-testers

Somewhere either in [config loaders](https://github.com/Trustroots/trustroots/tree/master/config) or [Express.js loader](https://github.com/Trustroots/trustroots/blob/master/config/lib/express.js) we'd have something like:

```js
var config = require('../config');
 
if (config.betaFeatures.length) {
  config.betaFeatures.forEach(function(betaFeature) {
    config.featureFlags[betaFeature] = true;
  });
}
```

Another way to go about this is to expose features via frontend only via feature-flags and at the API CRUD operations only for beta-users in policy file, since it's user-group aware:

https://github.com/Trustroots/trustroots/blob/3281c5c0a21cd87812b66040ddca2d1507b4a4ca/modules/messages/server/policies/messages.server.policy.js#L17-L53


  ...so in summary: it's not so simple. :-)
