### ISSUE TITLE
Resend account confirmation emails

### ISSUE THREAD

**Issue by doktorhorst** [Trustroots/trustroots#803]
Due to email delivery problems in Spring 2018, we have a lot (50-100) of support requests from that time from **people who were never able to confirm their account**.

We should resend them an account confirmation link to all emails linked to an unacticated account.

**Comment by simison** [comment]
Due to the nature of the failure (background job worker failing), those emails piled up in the queue and were sent out once the worker was functioning again. So folks probably got the emails at the end. Folks can also log in and re-send the confirmation email from their account page.

I think the system also tries to nudge them later on with another email if their profile is still unconfirmed (didn't check if that's the case).

If you can gather a list of emails or usernames, @guaka could probably check from the DB if any of them are still unconfirmed.

**Comment by doktorhorst** [comment]
I manually checked a few before writing this, and it seemed most of them are still unconfirmed (At least their profile page didn't exist).
If that nudging email you're mentioning exists, then we can close this, I think.
