### ISSUE TITLE
more consistent header menu, footer, styling

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#892]
Currently there seem to be various ways to present menus and navigation, I'm still kinda confused myself, at times when navigating (after almost 4 years). Good to make it more consistent.

_feel free to edit/add_
- [ ] keep menu a little bit more similar whether logged in or not, e.g. keep logo in top left when not logged in
- [ ] add header and footer to 404 page
- [ ] use footer space better (e.g. show deploy date) => #903 
- [ ] we will need to put language selector somewhere, good to be ready for that
- [ ] something with https://www.trustroots.org/signup - it looks quite different from the rest now

## currently

_edit this!_

### same for logged in and not logged in

- https://www.trustroots.org/not-found no header menu nor footer

### not logged in

- header menu has just Join and Login
- https://www.trustroots.org/signup doesn't have a menu or footer, nor any kind of styling at all really
- https://www.trustroots.org/search no footer (I didn't even know that /search does something when not logged in)

### logged in

- header menu with logo and many links
- https://www.trustroots.org/search no footer
- other pages have header menu and footer

**Comment by simison** [comment]
Nice, there's always plenty of space to improve navigation flows!

There's quite a bit of design consideration in the play here; I'll run through a few points and maybe flows and navigation start to show up more cohesively for ya. :-) Keep also in mind that about half the users see the mobile views and some see small'ish touchpad screen. 


> keep menu a little bit more similar whether logged in or not, e.g. keep logo in top left when not logged in

Would you see some other ways how these menus could be similar, than just the logo?

The goal when browsing the site is very different when authenticated in or not. All the UI for authenticated users should be gone for non-authenticated users and we mostly want folks to either login, or get to know what Trustroots is, and sign-up. When they're authenticated, the focus in the header should be on making it effective to use the site; not to show "FAQ", "Volunteer" etc links.

The logo is gone from the header indeed but it's to avoid repetition of "Trustroots" too much, e.g. on front page it's alredy twice above the fold:

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/87168/49118109-d57f0180-f2ab-11e8-9013-7402beccfa60.png">

So the header indeed should be very different depending if you're authenticated or not. Here's a similar examples from Facebook and Twitter:


<img width="1075" alt="screenshot 2018-11-28 at 01 25 13" src="https://user-images.githubusercontent.com/87168/49118319-7f5e8e00-f2ac-11e8-9e21-28999396845a.png">
<img width="1215" alt="screenshot 2018-11-28 at 01 25 04" src="https://user-images.githubusercontent.com/87168/49118320-7ff72480-f2ac-11e8-8d8c-c9b10aca4611.png">

<img width="939" alt="screenshot 2018-11-28 at 01 24 14" src="https://user-images.githubusercontent.com/87168/49118277-5fc76580-f2ac-11e8-99e2-2ba8cf0fb564.png">
<img width="1028" alt="screenshot 2018-11-28 at 01 23 39" src="https://user-images.githubusercontent.com/87168/49118278-5fc76580-f2ac-11e8-8002-42f83f983c5e.png">

Maybe you expected it to be more similar on desktop to what Twitter has?


> use footer space better

Footer is tricky because we show so often content that doesn't scroll; pretty much all UI on mobile, messages view, map search... A not very important footer would just float on top of taking space from something actually important. That's why we basically don't have footer, except on few more basic text pages:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/87168/49116784-58ea2400-f2a7-11e8-973f-2130afe81a67.png">

So since it's important to think how we build navigation without the footer anyway, we'd just be duplicating the content in footer and then probably hiding it again for mobile users.

Non authenticated users navigate the site mostly via frontpage:

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/87168/49116870-95b61b00-f2a7-11e8-8167-5933f88e9f53.png">

And they get back to that page via "read me" link in the header or since our pages are mostly 1 level deep, they'll likely just hit mobile device's return arrow.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/87168/49116894-a1a1dd00-f2a7-11e8-8748-b7b94b0cd26f.png">

This flow could be improved by:
- Improving footer content on home page; it's mostly convincing you to trust us and sign up, which is good. Things like "shop" and "volunteering" aren't probably super important for non-authenticated users, some FAQ content can be very important.
- "Read more" in the header could be more obvious; preferably it would behave more like "go back" arrow on applications for mobile and dropdown menu on desktop.
- The big "home page footer" could be repeated for non-authenticated desktop users on other pages, too.

Authenticated users navigate primarly via header on desktop:

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/87168/49118454-e8460600-f2ac-11e8-8de4-6bb05746986a.png">

or via header + "navigation" icon on mobile:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/87168/49118473-fb58d600-f2ac-11e8-818d-317a83ba7c6b.png">

For authenticated users the navigation flow could be improved, but it depends what content we want to drive and how much we want to damage the "daily usage" with cost of getting more visibilty for pages like "volunteer". We have a lot of features at this site already and would be pity to start hiding stuff like "meet" or "tribes" just because we ran out of header space...


> use footer space better (e.g. show deploy date)

Suppose the goal of "deploy date" would be to drive more volunteers? Wouldn't plain english "Volunteer" link work more effectively for that rather than deploy date that is very technical and not very useful for most people?


>we will need to put language selector somewhere, good to be ready for that

If you consider that most of the folks are logged in when using the site, we actually don't need language selector visible all the time. We'll need UI-language setting in somewhere but it can be first shown during signup and later in account page. 

For non-authenticated users we'll need it visible all the times but we have plenty of space at the header area for that.


>something with https://www.trustroots.org/signup - it looks quite different from the rest now

So do rest of the authentication related flows like login and "forgot password". When users are clicking through those flows, they're not looking for "volunteer" page but just trying to login/signup/restore their password, so rest of the UI should get out of their way at that point.

>https://www.trustroots.org/signup doesn't have a menu or footer, nor any kind of styling at all really

It _has_ styling, it's just making you to concentrate on texts and inputs and any background colours and such would just make it harder. :-) On pages like "login" we can afford littel bit more explosive design because there are just two inputs to fill.

---

So all those explanations aside, I am worried if you're feeling lost in navigation but maybe we can identify some gaps or dead ends there might be rather than just "make everything the same". :-) Keep in mind also that you're clicking around and regular user would either see the site as non-authenticated, or authenticated and not both.

Lemme also know if I missed something!

**Comment by simison** [comment]
I wanted to add that would be great to add search input directly in the header, letting users to jump either to location or user profile very quickly. But that kind of feature takes a lot of space, so we'd have to re-think the rest.
