### ISSUE TITLE
Encourage people to invite their friends to Trustroots

### ISSUE THREAD

**Issue by petr-hajek** [Trustroots/trustroots#947]
**Is your feature request related to a problem? Please describe.**
I want to invite my friends to TR. Currently I need to copy the link and write them an email.

**Describe the solution you'd like**
- Adding link to the user menu (under Account).
- This could reuse the previous invite page but without the information that TR is invite only.
- It'd send message with a link just to trustroots.org
- User could send it to several email addresses (up to 10?)

Add links to discussion on Slack (or Discourse).
https://trustroots.slack.com/archives/C08SENA9Z/p1544464961044100

**Comment by simison** [comment]
Stats for the AddThis widget when we had it (for like a year):

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/87168/49754145-043ea400-fcbe-11e8-8f45-75fda1e4f29e.png">

I guess folks these days don't really use email anymore. :-)

**Comment by simison** [comment]
PR with the JS code for the AddThis stuff:

https://github.com/Trustroots/trustroots/pull/874/files

**Comment by petr-hajek** [comment]
Yea, maybe we could build on it later on with invitations in messages to other platforms, like FB. Thinking about it, it's about the same work to copy TR url to your email as to copy email address to TR...

**Comment by simison** [comment]
>Thinking about it, it's about the same work to copy TR url to your email as to copy email address to TR...

😆  It does have some value though since it might work as a reminder or initiator to do that share that they might not otherwise do.

That said, we might get more shares like this when showing the share-buttons in more strategic places — a person does an action and something shows up and nudges them to share the tribe with their friends. Some example actions:
- _joins a tribe_ 
- _writes their first message_
- _adds their first contact_

**Comment by simison** [comment]
Renamed the issue title to reflect a bit more _intent_ rather than specific _task_.

**Comment by guaka** [comment]
Great place to have this after:

- _leaves a positive reference_
