### ISSUE TITLE
UI: Extra scrollbar when adding language to profile

### ISSUE THREAD

**Issue by petr-hajek** [Trustroots/trustroots#951]
**Describe the bug**
When adding a language to profile, there is a new scrollbar which you need to scroll to see the whole language list. Also the input field can be overflowing.

**To Reproduce**
1. Go to /profile/edit
2. Click into Languages input field

**Expected behavior**
Either the language list will be shorter or there is bigger margin so no extra scrollbar is displayed.

**Screenshots**
![selection_009](https://user-images.githubusercontent.com/38785076/49798793-79a08800-fd43-11e8-90b0-4dd3acb69213.png)

**Desktop (please complete the following information):**
FF 63.0.3 on Mint

**Comment by simison** [comment]
https://react-select.com

We use this external directive for it: https://github.com/leocaseiro/angular-chosen

Hope you don't mind that I'm marking this as "low" priority because:
- it's in Angular directive that will likely get rewritten to React soonish
- it's not blocking anyone from using the input

That said, totally fine if you'd like to fix it or even better — migrate it to React. :-) This seems pretty robust: https://react-select.com

Styles for this directive are here:
https://github.com/Trustroots/trustroots/blob/e5595852fdc550eab5c3390057d24c99e39650c6/modules/core/client/less/modules/chosen.less

Note that the same directive is used in search filters so that would need testing as well.
