### ISSUE TITLE
Show contacts on the map differently from other hosts

### ISSUE THREAD

**Issue by petr-hajek** [Trustroots/trustroots#958]
**Is your feature request related to a problem? Please describe.**
I want to look on the map of some place and immediately see my contacts in the area. It can be helpful since people move around a lot.

**Describe the solution you'd like**
Display the hosting contacts with different color (pink?). Later iteration could be to display contacts even when not hosting, but it'd be a question which location to use for them.
EDIT: Display different icon and if possible, we can also not let them get "grouped

**Comment by simison** [comment]
Yeah! 💯  I love it.


>Display the hosting contacts with different color (pink?).


How about something like this:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/87168/49894746-5f57ce80-fe57-11e8-93f4-fabc22bf65ed.png">

If possible, we can also not let them get "grouped".

I’m a bit hesitant to add new colours to dots because colours don’t inherently tell anything unless you’re familiar with them from the interface somehow. They also "override" the original color. For example "yes/maybe" -hosting colours are introduced in several places in the UI:

<img width="433" alt="image" src="https://user-images.githubusercontent.com/87168/49893130-611f9300-fe53-11e8-8133-044a0f8a44f7.png">

<img width="332" alt="image" src="https://user-images.githubusercontent.com/87168/49893148-6977ce00-fe53-11e8-816b-c64e21af1464.png">

<img width="848" alt="image" src="https://user-images.githubusercontent.com/87168/49893287-bcea1c00-fe53-11e8-9f4b-872ba2de2e45.png">

...and the map already has as many as 4 colours in use which is quite a bit to learn+remember: 

<img width="458" alt="image" src="https://user-images.githubusercontent.com/87168/49893448-14888780-fe54-11e8-97ab-21f4c433c3bb.png">

Noting that I also tested if border+highlight would look nice but it kinda still gets lost in the map:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/87168/49894205-05a2d480-fe56-11e8-9195-7fbbc1dfa45e.png">

**Comment by simison** [comment]
Related to _"show all the friends on the map, regardless of their hosting status"_ https://github.com/Trustroots/trustroots/issues/396

**Comment by guaka** [comment]
Very simple icons can overcome using more colors.

e.g.
/\ a roof icon for hosting
= your own contact
o someone who wants to meet (open)

**Comment by simison** [comment]
> Very simple icons can overcome using more colors.

Sure — these symbols should also be "introduced" and explained somehow in the interface just like colours would, since they carry more meaning than just _"somehow significant marker"_.

**Comment by noahsmindfuck** [comment]
I just figured that I have many contacts and that they change their location. Now that I am planning a longer trip I wondered whether any of my contacts are on my way or at least in reach.
It would be great to have only contacts shown with the same metric that does the on/off for tribes.
