### ISSUE TITLE
update Kasper's welcome message

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#979]
Gotta update this:
> 
> Hi guaka guaka!
> 
> I'm Kasper from the Trustroots Foundation. How are your first impressions from Trustroots — anything missing? If you have any feedback for us, you can simply reply to this email.
> 
> Trustroots is not only about hosting others but also about meeting community members. To make it easier for others to find you, you can create a meetup.
> 
> Like our Facebook page, join our Facebook group and follow us on Twitter or Instagram — it would really help us out!
> 
> Have a good one! Kasper 

- [ ] remove social media stuff (we have 118 followers on instagram, so doesn't really do much)
- [ ] instead, tell people to tell their friends about trustroots

**Comment by simison** [comment]
I'd keep FB page and/or group: when folks like posts in FB, their friends can see those posts, too. We have a pretty high conversion rate for folks coming from social networks according to GA.

**Comment by comradekingu** [comment]
>Hi guaka guaka!
>
>I'm Kasper from Trustroots, the foundation.
>
>What is your impression of Trustroots — anything missing?
>More than hosting, Trustroots is also about meeting and helping the community in a wider >sense. Share it with your friends.
>
>PS: To make it easier for others to find you, you can create a meetup.
>
>Have a good one! Kasper

Uguak ugak.

I am some Internet person, I think your message is good. If anyone else finds it in good taste, I would also appreciate how the challenge on the fourth wall is brought to a mere anecdotal imagery of presenting what is my own take on this message presented as someone else's.

Speaking for myself, I am glad no mention of unsocial network spying was mentioned, because I am on this libre software network to get away from proprietary overlord solutions (such as GitHub…)

I need no reminder of what I like, nor any reminder of sharing with my friends.
Sharing with my friends is what I do, that is what makes them my friends.
I know who I am, I know who my friends are. It appears you do not, and if you did, I wouldn't.
Assumptions about what kind of services I use are unflattering, by way of asking me to take up the time of others is more of the same. I am beholden to my friends directly, not through your system.

I multi-relatedly note the omission of "us", speaking on behalf of the foundation, as an active choice, and that "sharing it with your friends" made its way in as I was writing this.
