### ISSUE TITLE
Missing languages

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#98]
Language list is pretty well covering all common languages, but something might still be missing:

Add:
- [ ] Dutch (Flemish)
- [x] Esperanto
- [x] Latin
- [x] Ancient Greek
- [x] Creole languages
- [x] Sign languages
- [x] Serbo-Croatian
- [ ] Na'vi
- [ ] Aluku
- [ ] Wompanoag
- ?

**Comment by simison** [comment]
This one is a bit odd (for "Greek"):
>Modern Greek (1453-)

**Comment by simison** [comment]
>It's missing some languages that I speak: Aluku, one bushinengee language important here in French Guiana. As I'm learning and teaching for aluku kids, I would like to show it to my possible hosts, it's something that I offer in exchange.
>Also, French Creole and English Creole. It could be any creole tongue from any of the old colonies.

**Comment by simison** [comment]
>I wanted to add Esperanto to list of my languages, but did not find it in the selection.

**Comment by simison** [comment]
>There are no sign languages in languages to put in :-( Please add them whenever you can :-)

**Comment by simison** [comment]
@RichardLitt #290:
>I am unable to add Latin, Ancient Greek, or Na'vi to my languages. Granted, I am unlikely to speak those languages to a guest - but it's not impossible, and I would like to be able to add that I speak them. I also cannot add Wompanoag - a minority language, chosen at random and which I don't speak, with a few hundred speakers in Massachusetts.

>Adding the ability to add your own language by pressing enter would alleviate this issue.

**Comment by simison** [comment]
>the language spoken in Slovenia is "Slovene", while "Slovenian" means a person living in Slovenia.

**Comment by simison** [comment]
Got:
>Hi please add punjabi as one of language in language selection box. Thank you.

**Comment by simison** [comment]
Missing "Serbo-Croatian":

>I've noticed Serbian, Bosnian and Croatian are separate languages even though they are actually one language, Serbo-Croatian. So I suggest that you can copy CS on that one, offer BCMS languages separate (including Montenegrin which is not listed there) and also offer Serbo-Croatian, so that people can choose whatever they feel most comfortable with. And I feel like Serbo-Croatian is the best option for me personally because then I don't have to type that I speak four different languages and appear to be some super-multilingual person.
>
>Of course, if there are some reasons why you decided to skip Montenegrin and not offer Serbo-Croatian, that's cool too, I just wanted to offer my feedback and this link:
>
>https://en.wikipedia.org/wiki/Serbo-Croatian

**Comment by noahsmindfuck** [comment]
We got user feedback that "Chinese" is not actually a language and that it should be at least changed to 'Mandarin' or any of that kind. It would be like saying in Switzerland they speak 'Swiss'. How would I accomplish that?

**Comment by libertedeparole** [comment]
According to most Chinese sources, Chinese IS a language. The official Chinese government position is that varieties such as Mandarin and Cantonese be referred to as “dialects” of a single Chinese language. So it all depends on if you want to impose a Western schema on non-Western language(s).

**Comment by noahsmindfuck** [comment]
Can you refer to any kind of source for that or is it an opinion of yours?

**Comment by simison** [comment]
It's not a big deal to add all; "Chinese" and the major dialects to the list.

**Comment by libertedeparole** [comment]
According to most Chinese sources, Chinese IS a language. The official Chinese government position is that varieties such as Mandarin and Cantonese be referred to as “dialects” of a single Chinese language. So it all depends on if you want to impose a Western schema on non-Western language(s). 

> noahsmindfuck asked:
> 
> Can you refer to any kind of source for that or is it an opinion of yours?

It is a simple fact. 

If you read Chinese, you can consult official PRC sources.

Otherwise, you could start here:

"Chinese (simplified Chinese <https://en.wikipedia.org/wiki/Simplified_Chinese_characters>: 汉语; traditional Chinese <https://en.wikipedia.org/wiki/Traditional_Chinese_characters>: 漢語; pinyin <https://en.wikipedia.org/wiki/Pinyin>: Hànyǔ; literally: 'Han <https://en.wikipedia.org/wiki/Han_Chinese> language'; or Chinese: 中文; pinyin: Zhōngwén; literally: 'Chinese writing') is a group of related, but in many cases not mutually intelligible <https://en.wikipedia.org/wiki/Mutual_intelligibility>, language varieties <https://en.wikipedia.org/wiki/Variety_(linguistics)>, forming the Sinitic branch of the Sino-Tibetan language family <https://en.wikipedia.org/wiki/Sino-Tibetan_language_family>. Chinese is spoken by the ethnic Chinese <https://en.wikipedia.org/wiki/Han_Chinese> majority and many minority ethnic groups in China <https://en.wikipedia.org/wiki/China>. About 1.2 billion people (around 16% of the world's population) speak some form of Chinese as their first language <https://en.wikipedia.org/wiki/First_language>.
"The varieties of Chinese <https://en.wikipedia.org/wiki/Varieties_of_Chinese> are usually described by native speakers as dialects of a single Chinese language, but linguists note that they are as diverse as a language family <https://en.wikipedia.org/wiki/Language_family>." <https://en.wikipedia.org/wiki/Chinese_language#cite_note-4>

**Comment by libertedeparole** [comment]
> On 3 Apr 2019, at 13:58, Liberté de Parole <libertedeparole@gmail.com> wrote:
> 
> According to most Chinese sources, Chinese IS a language. 

Arabic is similar. Arabic is usually considered to be a single language, even though spoken varieties are often mutually unintelligible. Like Chinese, Arabic has a single dominant written form, even though this form does not correspond directly to any spoken dialect.

**Comment by simison** [comment]
Thanks for the insights, both! :heart:

Seems like we can add main languages + dialects for each group to our language list. 👍

**Comment by simison** [comment]
Question of adding "Taiwanese" came up. 

Then we found out that there's "Taiwanese Mandarin", "Taiwanese Hokkien", "Taiwanese Hakka" (and few other languages but smaller). 

Then I was looking for language codes for these (couldn’t find) and looked around what other sites do with these languages.
We have; “Chinese” (most Taiwanese member have this) but we’ve talked in past splitting Chinese into its sub-languages (Hokkien, Mandarin, etc).
These Taiwanese seem to be more like dialects of those, so this might get sorted by adding those Chinese variants? They also  have language codes and also used by other major websites.

**Comment by TMC89** [comment]
Reminder about the Taiwanese question. That member still didn't received an answer so I'll give her the heads up now that it's in the Github loop ;)

**Comment by TMC89** [comment]
Btw, Flemish isn't considered a form of Dutch, it's one of the two official languages spoken in Belgium: French and Flemish. Yes we understand each other and have many words in common, like Spanish and Portugese or American and British, but it's definitely not a Dutch dialect.

**Comment by TMC89** [comment]
Got an update about how we could include the Taiwanese language from the requested member through support:
_Taiwanese languages are listed in ISO 639. Actually there are a whole lot more languages in that standard than those available on BW, it even includes all dead languages like ancient Egyptian and such! So it's possible to make a custom list. The developer should be able to manually add Taiwanese to the site, including Hokkein, Hakka and other indigenous languages. What's more, Couchers.org has added Taiwanese, Hokkien and Hakka into their language option list.  Will Trustroots be able to do that too?_

**Comment by simison** [comment]
I think we're already including all the living languages from the [ISO 639 - 3](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Languages/List_of_ISO_639-3_language_codes_(2019)) list, and can see Hakka there at least. Did that change (in https://github.com/Trustroots/trustroots/pull/2494) to primarily include many of the dialects used in Taiwan, but it also brought hundreds of other new smaller languages to the list.

**Comment by TMC89** [comment]
Okay, as I understood, Hakka Chinese is a language that is connected to suppression for Taiwanese people, that is why she requests 'Taiwanese'. Is it possible to add that as well? I don't see it in the ISO list you mention but I do see BW has it as an option with their languages.
